#include <ansi.h>
inherit SKILL;
mapping *quest = ({
     ([ "quest":                HIY"钱"NOR,
        "quest_type":           "寻",
        "quest_location":		"南宫银庄",
        "exp_bonus":            2,
      ]),
     ([	"quest":		"店小二",
		"quest_type":		"杀",
		"quest_location":	"风云城",
		"exp_bonus":		2,
	]),
	([	"quest":		"无聊少年",
		"quest_type":		"杀",
		"quest_location":	"风云南城",
		"exp_bonus":		2,
	]),
	([	"quest":		"驼背老汉",
		"quest_type":		"杀",
		"quest_location":	"风云东城",
		"exp_bonus":		2,
	]),
	([	"quest":		"老裁缝",
		"quest_type":		"杀",
		"quest_location":		"风云南城",
		"exp_bonus":		2,
	]),
	([	"quest":		"卖药的",
		"quest_type":		"杀",
		"quest_location":		"风云东城",
		"exp_bonus":		2,
	]),
	([	"quest":		"胡英",
		"quest_type":		"杀",
		"quest_location":		"风云东城",
		"exp_bonus":		2,
	]),
	([	"quest":		"土娼",
		"quest_location":		"风云东城",
		"quest_type":		"杀",
		"exp_bonus":		2,
	]),
	([	"quest":		"鸭油包",
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		"小风车",
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		"羊头",
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		"内功心法",
		"quest_type":		"寻",
		"quest_location":		"警世书局",
                "exp_bonus":		2,
	]),
	([	"quest":		CYN"大青菜"NOR,
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		WHT"小白菜"NOR,
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		"纸钱",
		"quest_type":		"寻",
		"quest_location":		"风云东城",
                "exp_bonus":		2,
	]),
	([	"quest":		"包子",
		"quest_type":		"寻",
		"quest_location":		"风云城",
                "exp_bonus":		2,
	]),
	([	"quest":		"烤鸡腿",
		"quest_type":		"寻",
		"quest_location":		"风云城",
                "exp_bonus":		2,
	]),
        ([      "quest":                "收破烂的",
                "quest_type":           "杀",
                "quest_location":		"老屋或风云城",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "乞丐",
                "quest_type":           "杀",
                "quest_location":		"老屋",
                "exp_bonus":            2,
        ]),
        ([      "quest":                "小担贩",
                "quest_type":           "杀",
                "quest_location":		"风云西城外",
                "exp_bonus":            2, 
        ]),
	([	"quest":		GRN"黄瓜"NOR,
		"quest_type":		"寻",
		"quest_location":		"风云城",
                "exp_bonus":		2,
	]),
	([	"quest":		"妙手空空之技",
		"quest_type":		"寻",
		"quest_location":		"银钩赌坊",
		"exp_bonus":		2,
	]),
	([	"quest":		"蓝天鹅",
		"quest_location":	"黑松山下",
		"quest_type":		"寻",
		"exp_bonus":		2,
	]),
	([	"quest":		"黑牡丹",
		"quest_location":		"黑松山下",
		"quest_type":		"寻",
		"exp_bonus":		2,
	]),
	([	"quest":		"红枚瑰",
		"quest_location":		"黑松山下",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		"黄玫瑰",
		"quest_location":	"黑松山下",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		"紫罗兰",
		"quest_location":	"黑松山下",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		HIB"蓝天鹅"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
		"exp_bonus":		2,
	]),
	([	"quest":		BLU"黑牡丹"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
		"exp_bonus":		2,
	]),
	([	"quest":		HIR"红枚瑰"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		HIY"黄玫瑰"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		HIW"白茶花"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
	([	"quest":		HIM"紫罗兰"NOR,
		"quest_location":	"风云城或沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		2,
	]),
// end 2k
	([	"quest":		"李霞",
		"quest_location":	"关东老屋",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"醉汉",
		"quest_location":	"关东老屋",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"阿发",
		"quest_location":	"风云东城",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"大辫子姑娘",
		"quest_location":	"风云南城",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"老板娘",
		"quest_location":	"风云南城",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"牛皮酒袋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"泥人儿",
		"quest_location":	"风云东城",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"大酒袋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"魔法简介",
		"quest_location":	"警世书局",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"猪头",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"卤蛋",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"匕首",
		"quest_location":	"老屋",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"布袋",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"党参",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"玉棰子",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"胡老头",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		3,
	]),
	([	"quest":		"魔法简介",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
	([	"quest":		"猪头",	
		"quest_location":	"大胡子",
		"quest_type":		"寻",
                "exp_bonus":		3,
	]),
//end 3k
	([	"quest":		MAG"轻罗绸衫"NOR,
		"quest_location":	"千佛山下",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"张铁匠",
		"quest_location":	"风云南城",
		"quest_type":		"杀",
		"exp_bonus":		4,
	]),
	([	"quest":		"卖玩具的",
		"quest_location":	"风云东城",
		"quest_type":		"杀",
		"exp_bonus":		4,
	]),
	([	"quest":		"龙小云",
		"quest_location":	"眉峰聚",
		"quest_type":		"杀",
		"exp_bonus":		4,
	]),
	([	"quest":		"素菜包",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"牛头",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"轻功简介",
		"quest_location":	"警世书局",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"纸花",
		"quest_location":	"风云棺材店",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"符咒入门",
		"quest_location":	"警世书局",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"买鱼的小姑娘",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		4,
	]),
    ([     "quest":       "千金小姐",
        	"quest_location":	"千佛山下",
            "quest_type":           "杀",
            "exp_bonus":            4,   
        ]),
        ([	"quest":		"轻功简介",
		"quest_location":	"警世书局",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"当归",
		"quest_location":	"沉香镇药店",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	([	"quest":		"面条",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		4,
	]),
	
//end 4k
	([  "quest":                "小炒粉丝",
		"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "落第书生",
        	"quest_location":	"武当前院",
                "quest_type":           "寻",
                "exp_bonus":            5,
        ]),
        ([      "quest":                "抓破美人脸",
        	"quest_location":	"武当前院",
                "quest_type":           "寻",
                "exp_bonus":            5,
        ]),
	([	"quest":		"阿菜哥",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		5,
	]),
	([	"quest":		"穿开裆裤的小孩儿",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		5,
	]),
	([	"quest":		"磨菜刀的",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		5,
	]),
	([	"quest":		"杞子",
		"quest_location":	"沉香镇药店",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"淮山",
		"quest_location":	"沉香镇药店",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),	
	([	"quest":		"北芪",
		"quest_location":	"沉香镇药店",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),		
	([	"quest":		"大米",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"糙面",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"北芪",
		"quest_location":	"沉香镇药店",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"石狮子",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"生煎包",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"刨花油",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		RED"番茄"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		MAG"胡萝卜"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		HIR"胭脂"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),	
	([	"quest":		"生煎包",
		"quest_location":	"薛陀子",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		"刨花油",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		RED"番茄"NOR,
		"quest_location":	"卖菜的",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		MAG"胡萝卜"NOR,
		"quest_location":	"卖菜的",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
	([	"quest":		HIR"胭脂"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		5,
	]),
//end 5k
	([	"quest":		"大棉袄",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		6,
	]),
	([	"quest":		"李一摸",
		"quest_location":	"关东老屋",
		"quest_type":		"杀",
		"exp_bonus":		6,
	]),
	([	"quest":		"知客僧",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		6,
	]),
	([	"quest":		"小笼包",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		6,
	]),
	([	"quest":		"小碟儿",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		6,
	]),
	([	"quest":		"油油的纸",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		6,
	]),
	([	"quest":		"谷慧儿",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		6,
	]),
	([	"quest":		"金瓶梅",
		"quest_location":	"风云城",
		"quest_type":		"寻",
        "exp_bonus":		6,
	]),   
//end 6k
        ([  "quest":            "灰布僧衣",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "忏悔徒",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            7,   
        ]),
        ([      "quest":                "雅芳",
        	"quest_location":	"风云城",
                "quest_type":           "杀",  
                "exp_bonus":            7,     
        ]),
        ([      "quest":                "香客",
        	"quest_location":	"嵩山",
                "quest_type":           "杀",  
                "exp_bonus":            7,     
        ]),
	([	"quest":		"袁姬",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		7,
	]),
	([	"quest":		"农家女",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		7,
	]),
	([	"quest":		"韭菜合子",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"石牛",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"大蟑螂",
		"quest_location":	"风云城",
		"quest_type":		"杀",
		"exp_bonus":		7,
	]),
	([	"quest":		"小蟑螂",
		"quest_location":	"风云城",
		"quest_type":		"杀",
		"exp_bonus":		7,
	]),
	([	"quest":		"花粉袋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"狗皮膏药",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"花生",
		"quest_location":	"风云城驼背老汉",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		YEL"龙井茶"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"鸡肉包",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"桃符纸",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"九截鞭",
		"quest_location":	"风云城外",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"石牛",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"花粉袋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"狗皮膏药",
		"quest_location":	"大胖子",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"花生",
		"quest_location":	"风云城驼背老汉",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		YEL"龙井茶"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"玉蒲团",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
	([	"quest":		"九截鞭",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		7,
	]),
//end 7k
        ([      "quest":                "伙计",
        	"quest_location":	"风云城",
                "quest_type":           "杀",  
                "exp_bonus":            8,     
        ]),
        ([      "quest":                "黑色劲装",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "年青人",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "六角锤",
        		"quest_location":	"黑松山",
                "quest_type":           "寻",
                "exp_bonus":            8,
                "difficulty":           30,   
        ]),
        ([	"quest":		"挑水的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"念经的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"打杂的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"扫地的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"砍柴的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"朝拜的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"高人",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"烧饭的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"淘米的和尚",
		"quest_location":	"千佛山",
		"quest_type":		"杀",
		"exp_bonus":		8,
	]),
	([	"quest":		"扫把",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		8,
	]),
	([	"quest":		"蚯蚓",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		8,
	]),
	([	"quest":		"竹夫人",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		8,
	]),
        ([      "quest":            "丧尽天良的畜生",
                "quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            8,   
        ]),
        ([      "quest":                "登山者",
                "quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "石灰石",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            8,
        ]),
        ([      "quest":                "谷子",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            8,
        ]),
//end 8k
	([	"quest":		"芦苇",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		HIR"断肠草"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"锦囊",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"卖馕的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	([	"quest":		"卖花帽的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	([	"quest":		"卖小刀的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	([	"quest":		"卖库车白杏的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	([	"quest":		"烤羊肉串",
		"quest_type":		"寻",
		"quest_location":	"新疆",
        "exp_bonus":		9,
	]),
	([	"quest":		"卖葡萄干的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	    ([      "quest":                "老乞丐",
                "quest_type":           "杀",
                "quest_location":		"泰山",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "柳若松",
        		"quest_location":	"泰山",
                "quest_type":           "杀",
                "difficulty":           50,
                "exp_bonus":            9,
        ]),
        ([      "quest":                "大老板",
        		"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            9,
                "difficulty":           50,
        ]),
        ([      "quest":                "采花妞",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            9,
        ]),
        ([      "quest":                "紫花瓣儿",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            9,
        ]),
        ([	"quest":		"裸体女人",
        	"quest_location":	"风云城",
		"quest_type":		"杀",
		"exp_bonus":		9,
	]),
	([	"quest":		"旧书",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"小黄瓜",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"蓑衣",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"草鞋",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"茶花",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"烧饼",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),	
	([	"quest":		"水壶",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),	
	([	"quest":		"崩了口的小碟儿",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"罗卜条",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"煮熟了的蛆",
		"quest_location":	"风云城大胡子",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
	([	"quest":		"铁斧",
		"quest_location":	"关外",
		"quest_type":		"寻",
                "exp_bonus":		9,
	]),
//end 9k
	([	"quest":		"卖戒指的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"卖烤包子的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"卖抓饭的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"卖哈密瓜的",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"雪蛤蟆",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
        "exp_bonus":		10,
	]),
	([	"quest":		"农具店老板",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"沉香镇的地头蛇",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		10,
	]),
	([	"quest":		"大理石",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
	([	"quest":		"鸡毛毽子",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
	([	"quest":		"砍柴刀",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
	([	"quest":		"信",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
	([	"quest":		"残破古画",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
	([	"quest":		"雷火珠",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		10,
	]),
        ([  "quest":                "花匠",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "彩裙",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            10,   
        ]),
        ([      "quest":                "采菱女",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "缅玉弧",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "烤羊腿",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "杨老太",
        	"quest_location":	"沉香镇",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "活剥皮",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "绍兴女儿红",
        	"quest_location":	"富贵山庄",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "酱牛肉",
        	"quest_location":	"富贵山庄",
                "quest_type":           "寻",
                "exp_bonus":            10,
        ]), 
        ([      "quest":                "彩裙",
				"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            10,   
        ]),
        ([      "quest":                "王虎",
        		"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "柳夫人",
        		"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            10,
        		"difficulty":           50,
        ]),
//end 10k
		([	"quest":		"哈密瓜",
		"quest_location":	"乌拉泊",
		"quest_type":		"寻",
        "exp_bonus":		11,
	]),
	([	"quest":		"卡你瓦依衣",
		"quest_location":	"乌拉泊",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"单刀",
		"quest_location":	"镇风兵器铺",
		"quest_type":		"寻",
        "exp_bonus":		11,
	]),
	([	"quest":		"抓饭",
		"quest_location":	"乌拉泊",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"葡萄干",
		"quest_location":	"乌拉泊",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"萤火虫",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		11,
	]),
	([	"quest":		"大雁",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		11,
	]),
	([	"quest":		"软红",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		11,
	]),
	([	"quest":		"昭红",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		11,
	]),
	([	"quest":		"蝉翼纱衣",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"勿忘我",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"石榴裙",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		11,
	]),
	([	"quest":		"七星锤",
		"quest_location":	"黑松堡",
		"quest_type":		"寻",
         "exp_bonus":		11,
         "difficulty":           30,
	]),
	([	"quest":		"青衣家丁",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		11,
		"difficulty":           50,
	]),
        ([      "quest":                "竹叶青酒袋",
        	"quest_location":	"富贵山庄",
                "quest_type":           "寻",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "如意客栈老板",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "老屋人",
        	"quest_location":	"关东老屋",
                "quest_type":           "杀",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "关东大汉",
        	"quest_location":	"关东老屋",
                "quest_type":           "杀",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "血肠",
        	"quest_location":	"关东老屋",
                "quest_type":           "寻",
                "exp_bonus":            11,
        ]),
        ([      "quest":                "小绵羊",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            11,
        ]),
                ([	"quest":		"小羊羔",
        	"quest_location":	"关外",
             "quest_type":           "杀",
                "exp_bonus":            11,
        ]),
          
//end 11k
	([	"quest":		"蓝衣家丁",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		12,
		"difficulty":           50,
	]),
	([	"quest":		"发黄的纸",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		12,
	]),
	([	"quest":		"琴儿",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		12,
	]),
	([	"quest":		"草编蚂蚱",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
                "exp_bonus":		12,
	]),
	([	"quest":		HIC"无影神针"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		12,
	]),
	([	"quest":		"护心镜",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		12,
	]),
        ([      "quest":                "战魂",
        	"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            12,
        ]),     
        ([      "quest":                "极乐逍遥散",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "化尸粉",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "夜行衣",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "精钢飞刀",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            12,
        ]),
        ([      "quest":                "红嘴小麻雀",
        	"quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            12,
        ]),
//end 12k
	([      "quest":                "杀人蜂",
        	"quest_location":	"帝王谷",
                "quest_type":           "杀",
                "exp_bonus":            13,
   ]),  
	([	"quest":		"樱桃",
		"quest_location":	"泰山",
		"quest_type":		"寻",
		"exp_bonus":		13,
	]),
	([	"quest":		"蛐蛐",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		13,
	]),
	([	"quest":		"蜜蜂",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		13,
	]),
	([	"quest":		"小宝儿",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		13,
	]),
	([	"quest":		"锦衣",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
		"exp_bonus":		13,
	]),
	([	"quest":		HIC"鬼牙玄冥杖"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
		"exp_bonus":		13,
	]),
	([	"quest":		"冰心诀",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
		"exp_bonus":		13,
	]),
        ([      "quest":                "武林小豪杰",
        	"quest_location":	"沉香镇",
                "quest_type":           "杀",
                "exp_bonus":            13,  
        ]),
        ([      "quest":                "云游僧人",
        	"quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "迎客僧",
        	"quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "紫衣家丁",
        		"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            13,
                "difficulty":           50,
        ]),
        ([      "quest":                "八楞玄铁锤",
	        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            13,
    			"difficulty":           30,
        ]),
	([	"quest":		"水手",
		"quest_location":	"千金楼或南海",
		"quest_type":		"杀",
                "exp_bonus":		13,
	]),
	([	"quest":		"丫环",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		13,
	]),
	([	"quest":		"老汉",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
                "exp_bonus":		13,
	]),
        ([      "quest":		"彭长净",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            13,
        ]),
        ([      "quest":                "宋长清",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            13,
        ]),
//end 13k
        ([	"quest":		"扫阶的道士",
		"quest_location":	"三清",
		"quest_type":		"杀",
		"exp_bonus":		14,
	]),
        ([      "quest":                "灰布道袍",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            14,
        ]),
        ([      "quest":                "青锋剑",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            14,
        ]),
	([	"quest":		"高粱酒袋",
		"quest_location":	"武当",
		"quest_type":		"寻",
		"exp_bonus":		14,
	]),
	([	"quest":		"嫩藕",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		14,
	]),
	([	"quest":		"卜亚男",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		14,
	]),
	([	"quest":		"兰儿",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		14,
	]),
	([	"quest":		"燕儿",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		14,
	]),
	([	"quest":		"商人",
		"quest_location":	"塞口",
		"quest_type":		"杀",
		"exp_bonus":		14,
	]),
	([	"quest":		"舍利子",
		"quest_location":	"关外",
		"quest_type":		"寻",
                "exp_bonus":		14,
	]),
	([	"quest":		"藏香",
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
                "exp_bonus":		14,
	]),
	([	"quest":		"茶砖",
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
                "exp_bonus":		15,
	]),
	([	"quest":		"蛇药",
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
         "exp_bonus":		15,
	]),
	([	"quest":		"鱼线",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		15,
	]),
	([	"quest":		"桃花枝",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		15,
	]),
        ([      "quest":                "水蛇",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "人影",
        	"quest_location":	"天枫",
                "quest_type":           "杀",  
                "exp_bonus":            15,  
        ]),
        ([      "quest":                "白绸长披风",
                "quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),        
        ([      "quest":                "破旧不堪的长衣",
                "quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "米酒",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "麋角散",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "水桂",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "缅玉镯",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "缅玉指",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "缅玉花",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),                
//end 15k
	([      "quest":                "热气腾腾的鲫鱼汤",
        	"quest_location":	"无名小镇",
                "quest_type":           "寻",
                "exp_bonus":            15,
        ]),
	([	"quest":		"恶魔亡魂",
		"quest_location":	"帝王谷",
		"quest_type":		"杀",
                "exp_bonus":		16,
	]),
	([	"quest":		"葱花",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"梭子",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"细麻线",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"水晶球",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"火摺子",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"镰刀",
		"quest_location":	"桃源或沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([      "quest":                "绣满了元宝的绸大褂",
		"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "韩掌柜",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "俊俏相公",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            16,
        ]),
        ([      "quest":                HIC"相公袍"NOR,
        	"quest_location":	"富贵山庄",
                "quest_type":           "寻",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "大厨",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "卤味儿",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "雅公子",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "摺扇",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "俏鸨母",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            16,
        ]),
        ([      "quest":                "舞蝶彩衫",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            16,
        ]),
	([	"quest":		"小炒粉丝",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"油辣猪排",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"椒盐排骨",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),
	([	"quest":		"锦绣鱼丝",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		16,
	]),	
	([	"quest":		"魏宝宝",
		"quest_location":	"老屋或武当",
		"quest_type":		"杀",
		"exp_bonus":		16,
	]),
	([	"quest":		"魏包包",
		"quest_location":	"老屋或武当",
		"quest_type":		"杀",
		"exp_bonus":		16,
	]),
//end 16k
	([      "quest":                "热气腾腾的青菜",
        	"quest_location":	"无名小镇",
                "quest_type":           "寻",
                "exp_bonus":            18,
        ]),
	([	"quest":		"小钩子",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
	([	"quest":		"藤萝绳",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
	([	"quest":		"桃花瓣",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
	([	"quest":		"绣花针",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
	([	"quest":		"蘑菇",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
        ([      "quest":                "大绵羊",
                "quest_location":	"关外",
                "quest_type":           "杀",    
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "驼背老人",
                "quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "小翠",
        	"quest_location":	"铁雪山庄",
                "quest_type":           "杀",
                "exp_bonus":            18,  
                "difficulty":           50,
        ]),
        ([      "quest":                "绣花鞋",
        	"quest_location":	"铁雪山庄",
                "quest_type":           "寻",  
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "粉红衫",
        	"quest_location":	"铁雪山庄",
                "quest_type":           "寻",
                "exp_bonus":            18,  
        ]),
        ([      "quest":                "细梅剑",
        	"quest_location":	"铁雪山庄",
                "quest_type":           "寻",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "牧羊女",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "牧羊鞭",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            18,
        ]),
        ([      "quest":                "羊毛裙",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            18,
        ]),
	([	"quest":		"大箱子",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		18,
	]),
//end 18k
        ([	"quest":		"陶宝宝",
		"quest_location":	"老屋或武当",
		"quest_type":		"杀",
		"exp_bonus":		20,
	]),
	([	"quest":		"陶包包",
		"quest_location":	"老屋或武当",
		"quest_type":		"杀",
		"exp_bonus":		20,
	]),
	([	"quest":		"白毛巾",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
	([	"quest":		"胖老头",
		"quest_location":	"风云城外",
		"quest_type":		"杀",
		"exp_bonus":		20,
	]),
        ([      "quest":                "护寺藏尼",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "阴经",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "大红尼袍",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "古城烧",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "贾员外的女儿",
        	"quest_location":	"沉香镇",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "云母粉",
        	"quest_location":	"沉香镇",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([	"quest":		"乳香鲳鱼",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
	([	"quest":		"陈皮大虾",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
	([	"quest":		"果汁鱼球",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
	([	"quest":		"粗布道袍",
		"quest_location":	"岱庙",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),  
        ([      "quest":                "乌拉泊商人",
        	"quest_location":	"新疆",
                "quest_type":           "杀",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "英吉沙小刀",
        	"quest_location":	"新疆",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "馕",
        	"quest_location":	"新疆",
                "quest_type":           "寻",
                "exp_bonus":            20,
        ]),       
        		([	"quest":		"天香续命露",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
	([	"quest":		"油皮袋",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		20,
	]),
([      "quest":                "食人鱼",
        	"quest_location":	"帝王谷",
         "quest_type":           "杀",
           "exp_bonus":            20,
]),  	
//end 20k
	([      "quest":                "热气腾腾的大米饭",
        	"quest_location":	"无名小镇",
                "quest_type":           "寻",
                "exp_bonus":            23,
        ]),
	([	"quest":		"小竹拂尘",
		"quest_location":	"岱庙",
		"quest_type":		"寻",
                "exp_bonus":		23,
	]),  
	([	"quest":		"排骨面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		23,
	]),  
	([	"quest":		CYN"豹牙手环"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		23,
	]),
	([	"quest":		"瘦马",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
	([	"quest":		"断肠人",
		"quest_location":	"清平山庄",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
	([	"quest":		"家奴",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
	([	"quest":		"家奴短褂",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"大老鼠",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
	([	"quest":		"人皮酒袋",
		"quest_location":	"黑松堡",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"烤山猪肉",
		"quest_location":	"黑松堡",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"鱼骨头",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"蜡烛",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"菜刀",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
	([	"quest":		"葱油饼",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		23,
	]),
       ([       "quest":                "小渔",
       		"quest_location":	"南海",
                "quest_type":           "杀",
                "exp_bonus":            23,  
        ]),		 
        ([      "quest":                "沙罗门",
        	"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            23,
        ]),
        ([      "quest":                "小白兔",
        	"quest_location":	"大旗谷",
                "quest_type":           "杀",
                "exp_bonus":            23,  
        ]),
        ([      "quest":                "蝴蝶",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            23,
        ]),
        ([	"quest":		"上茶的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
	([	"quest":		"扫地的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		23,
	]),
        ([      "quest":                "许廉龙",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            23,
        ]),
//end 23k
        ([	"quest":		"牛肉面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		25,
	]),  
	([	"quest":		"虎纹鱼",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		25,
	]),
	([	"quest":		"鲇鱼",
		"quest_location":	"桃源",
		"quest_type":		"寻",
		"exp_bonus":		25,
	]),
	([      "quest":                "渔夫",
		"quest_location":	"东海",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                HIW"马面"NOR,
                "quest_location":	"地府",
                "quest_type":           "杀",
                "exp_bonus":            25,
                "difficulty":           50,
        ]),
        ([      "quest":                HIW"牛头"NOR,
                "quest_location":	"地府",
                "quest_type":           "杀",
                "exp_bonus":            25,
                "difficulty":           50,
        ]),
        ([      "quest":                HIR"铁索"NOR,
                "quest_location":	"地府",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                HIR"枷铐"NOR,
                "quest_location":	"地府",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "陆五川",
        	"quest_location":	"清平山庄",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "贾员外",
        	"quest_location":	"沉香镇",
                "quest_type":           "杀",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "黑色庄服",
        	"quest_location":	"清平山庄",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "风筝",
        	"quest_location":	"清平山庄",
                "quest_type":           "寻",
                "exp_bonus":            25,
        ]),
        ([	"quest":		"小竹拂尘",
		"quest_location":	"岱庙",
		"quest_type":		"寻",
                "exp_bonus":		25,
	]),  
		([	"quest":		"烤包子",
		"quest_location":	"新疆",		
		"quest_type":		"寻",
                "exp_bonus":		25,
	]),
	([	"quest":		"抓饭",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		25,
	]),
	([	"quest":		"葡萄干",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		25,
	]),
//end 25k
        ([	"quest":		"烧饭的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		28,
	]),
	([	"quest":		"挑水的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		28,
	]),
	 ([      "quest":			"孤魂",
       		"quest_location":	"新疆",
                "quest_type":           "杀",
                "exp_bonus":            28,
]),
        ([      "quest":                "碑文拓本",
                "quest_location":	"少林寺",
                "quest_type":           "寻",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "江湖中人",
        	"quest_location":	"少林寺",
                "quest_type":           "杀",
                "exp_bonus":            28,
        ]),
       	([	"quest":		"船桨",
       		"quest_location":	"风云外城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"苗刀",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"信鸽",
		"quest_location":	"黑松堡",
		"quest_type":		"杀",
		"exp_bonus":		28,
	]),
	([	"quest":		"小青菜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"梅树幼苗",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"铁镐",
		"quest_location":	"桃源",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
        ([      "quest":                "胡生",
        	"quest_location":	"南海",
                "quest_type":           "杀",
                "exp_bonus":            28,
        ]),
        ([      "quest":                "喀巴沙",
                "quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            28,
        ]), 
        ([      "quest":                "道士",
                "quest_location":	"三清宫",
                "quest_type":           "杀",
                "exp_bonus":            28,
        ]),       
	([	"quest":		"椒盐面筋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
		([	"quest":		"忘魂花",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		HIG"忘魂果"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"蚧味鱼米",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"清炒虾仁",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"脯雪黄鱼",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"青瓷大碗",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),
	([	"quest":		"鱼香肉丝",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		28,
	]),			
//end 28k
        ([	"quest":		"粗布道袍",
		"quest_location":	"岱庙",
		"quest_type":		"寻",
                "exp_bonus":		31,
	]),   
       ([      "quest":                "王莹",
       		"quest_location":	"黄山",
                "quest_type":           "杀",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "燕珊",
        	"quest_location":	"黄山",
                "quest_type":           "杀",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "红烧牛肉",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "紫衫",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            31,
        ]),        
        ([      "quest":                "蒙古人",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "不丹人",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            31,
        ]),
        ([      "quest":                "汉人",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            31,
        ]),
        ([      "quest":                BLK"黑郁金香"NOR,
        	"quest_location":	"南海",
                "quest_type":           "寻",
                "exp_bonus":            31,
        ]),
//end 31k        
	([	"quest":		"皮水袋",
		"quest_location":	"泰山",
		"quest_type":		"寻",
                "exp_bonus":		32,
	]),  
	([	"quest":		"水饺",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		32,
	]), 
	([	"quest":		"砍柴的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		32,
	]),
	([	"quest":		"淘米的道士",
		"quest_location":	"岱庙",
		"quest_type":		"杀",
		"exp_bonus":		32,
	]),       
        ([      "quest":                BLK"黑郁金香"NOR,
		"quest_location":	"南海小镇",
                "quest_type":           "寻",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "湖上草",
		"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "草衫",
		"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "湖上花",
		"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            32,
        ]),
        ([      "quest":                "花衫",
		"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            32,
        ]),
        ([	"quest":		"钥匙",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
		"exp_bonus":		32,
	]),
	([	"quest":		"小鸟蛋",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
		"exp_bonus":		32,
	]),
// end 32k        
        ([      "quest":                "湖上酒",
                "quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "酒衫",
                "quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            34,
        ]),
        ([      "quest":                "园工剪",
                "quest_location":	"黑松堡",
                "quest_type":           "寻",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "小园工",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",  
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "女佣人",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            34,   
        ]),
        ([      "quest":                "鸡毛",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",  
                "exp_bonus":            34,   
        ]),
	([	"quest":		"小白菜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		34,
	]),
	([	"quest":		"半干的木柴",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		34,
	]),
	([	"quest":		"小西门",
		"quest_location":	"万梅山庄",
		"quest_type":		"杀",
		"exp_bonus":		34,
	]),
	([	"quest":		"小兜兜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		34,
	]),
//end 34k
	([	"quest":		"辣酱面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		36,
	]),  
	([	"quest":		"小面馆的地契",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"开裆裤",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"风清",
		"quest_location":	"兴国禅寺",
		"quest_type":		"杀",
		"exp_bonus":		36,
	]),
	([	"quest":		"大青菜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"绣着梅花的浴巾",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"白玉小马桶",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"大白菜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"干木柴",
		"quest_location":	"万梅山庄",	
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"梅木长凳",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"路边的野花",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		36,
	]),
	([	"quest":		"椒盐面筋",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
	([	"quest":		"蚧味鱼米",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
        ([      "quest":                "钝剑",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "护院",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            37,
        ]),
        ([      "quest":                "小短剑",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            37,
        ]),
	([      "quest":                "厨子",
		"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            37,
        ]),
        ([	"quest":		"勿忘我",
        	"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
	([	"quest":		"月玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
	([	"quest":		"女玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
	([	"quest":		"草玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		37,
	]),
//end 37k
        ([	"quest":		"馄饨",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		41,
	]),  
        ([      "quest":                "碧玉刀",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),
	([	"quest":		"豌豆",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"枯黄的叶",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"青豆",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"韭菜",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
        ([      "quest":                "护寺喇嘛",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "大红僧袍",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "阳经",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "烧鸡",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),
        ([      "quest":                "大馒头",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),  
        ([      "quest":                "开花蚕豆",
        	"quest_location":	"华山",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),        
        ([      "quest":                "小云雀",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            41,
        ]),
        ([      "quest":                HIW"哈达"NOR,
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            41,
        ]),
        ([	"quest":		"麻绳",
        	"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"半干的血滴",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"马鬃木刷",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
	([	"quest":		"绿豆苗",
		"quest_location":	"万梅山庄",
		"quest_type":		"寻",
		"exp_bonus":		41,
	]),
//end 41k
	([	"quest":		"鸡丁面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]), 
	([	"quest":		"新疆地毯",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"装马奶子的皮袋",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"椒盐花生",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"牛肉面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"库车白杏",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"野人参",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"熊掌",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"鹿茸",
		"quest_location":	"关东老屋",
		"quest_type":		"寻",
                "exp_bonus":		45,
	]),
	([	"quest":		"浪游诗人",
		"quest_location":	"风云城外",
		"quest_type":		"杀",
		"exp_bonus":		46,
	]),
        ([      "quest":                "雪蹄胭脂马",
                "quest_location":	"千佛山",
                "quest_type":           "杀",
                "exp_bonus":            46,
        ]),
        ([	"quest":		"准葛儿商人",
		"quest_location":	"塞口",
		"quest_type":		"杀",
		"exp_bonus":		46,
	]),
	([	"quest":		"西夏商人",
		"quest_location":	"塞口",
		"quest_type":		"杀",
		"exp_bonus":		46,
	]),
        ([      "quest":                "牛皮马鞍",
        	"quest_location":	"千佛山",
                "quest_type":           "寻",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "文人墨客",
        	"quest_location":	"泰山",
                "quest_type":           "杀",
                "exp_bonus":            46,
        ]),
        ([      "quest":                "风凌",
        	"quest_location":	"兴国禅寺",
                "quest_type":           "杀",
                "exp_bonus":            46,
        ]),
//end 46k
	([	"quest":		"排骨面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]), 
	([	"quest":		"水饺",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]), 
	([      "quest":                "癞蛤蟆",
                "quest_location":	"太平镇",
                "quest_type":           "杀",
                "exp_bonus":            50,
        ]), 
        ([      "quest":                "探险者",
                "quest_type":           "杀",
                "quest_location":	"华山",
                "exp_bonus":            50,
        ]),
	([	"quest":		"毒蛇",
		"quest_location":	"泰山",
		"quest_type":		"杀",
		"exp_bonus":		50,
	]),
	([	"quest":		"考生",
		"quest_location":	"风云城",
		"quest_type":		"杀",
		"exp_bonus":		50,
	]),
	([	"quest":		"小金杯",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]),
	([	"quest":		"大酒碗",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]),
        ([      "quest":                "高粱酒袋",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "单身趟子手",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "趟子手",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "货票",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "高丽香蕉",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),  
        ([      "quest":                "银巢红珠",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),        
        ([      "quest":                "川味肝片",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),  
        ([      "quest":                "脆皮草鱼",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "芙蓉鳝片",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),        
        ([      "quest":                "生烧青鱼",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            51,
        ]),                                      
        ([      "quest":                "樊夫人",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "罗达成",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "苏玛",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
        ([      "quest":                "马鲁",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            51,
        ]),
//end 51k
	([      "quest":                "鹅蛋",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]), 
        ([      "quest":                "鹌鹑蛋",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]), 
        ([      "quest":                "鸡蛋",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            55,
        ]), 
	([	"quest":		HIR"杀手剑"NOR,
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		55,
	]),
	([	"quest":		"杀手牌",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		55,
	]),
	([	"quest":		"瘦嫖客",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		55,
	]),
	([	"quest":		"胖嫖客",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		55,
	]),
	([	"quest":		"吐鲁番少女",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		55,
	]),
	([	"quest":		"玉凹子",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		55,
	]),
	([      "quest":                "挑山夫",
        	"quest_location":	"岱庙",
                "quest_type":           "杀",
                "exp_bonus":            55,
        ]),
        ([	"quest":		"开花蚕豆",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]), 
	([	"quest":		"椒盐花生",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		50,
	]), 
//end 55k
        ([      "quest":                "风静",
        	"quest_location":	"兴国禅寺",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "田心",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "园工",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "粗木扁担",
        	"quest_location":	"岱庙",
                "quest_type":           "寻",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "长剪",
        	"quest_location":	"黑松堡",
                "quest_type":           "寻",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "黄衣卫",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "金钱袍",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "长剑",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "黑狗",
        	"quest_location":	"幽灵山庄",
                "quest_type":           "杀",
                "exp_bonus":            60,
        ]),
	([	"quest":		"胡刀",
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
                "exp_bonus":		60,
	]),
	([	"quest":		HIY"五"+HIR"彩"NOR+"紧身裙",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		60,
	]),
	([	"quest":		"风云马褂",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		60,
	]),
	([	"quest":		"辣酱面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		60,
	]),
	([	"quest":		"田膨郎",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		60,
	]),
	([	"quest":		"散花少女",
		"quest_location":	"白云",
		"quest_type":		"杀",
		"exp_bonus":		60,
	]),
//end 60k
	([	"quest":		"鳄鱼",
		"quest_location":	"千金楼",
		"quest_type":		"杀",
		"exp_bonus":		65,
	]),
       ([      "quest":                "响尾蛇",
        	"quest_location":		"大漠风沙",
                "quest_type":           "杀",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "大汉",
        	"quest_location":		"武当",
                "quest_type":           "杀",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "树枝",
        	"quest_location":		"武当",
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "塔僧",
        	"quest_location":		"关外",
                "quest_type":           "杀",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "湖上草",
        	"quest_location":		"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "草衫",
        	"quest_location":		"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "湖上花",
        	"quest_location":		"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "花衫",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "水饺",
        	"quest_location":	"华山",
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "鸭蛋",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            65,
        ]),
//end 65k
	([	"quest":		"铜哨",
		"quest_location":	"幽灵山庄",
		"quest_type":		"寻",
		"exp_bonus":		71,
	]),
	([	"quest":		"哈密瓜",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		71,
	]),
	([	"quest":		"卡你瓦依衣",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		71,
	]),
	([	"quest":		"牛皮袋",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		71,
	]),
	([	"quest":		"装酸奶子的皮袋",
		"quest_location":	"新疆",
		"quest_type":		"寻",
                "exp_bonus":		71,
	]),
        ([      "quest":                "水灵光",
        	"quest_location":	"大旗谷",
                "quest_type":           "杀",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "湖上女",
                "quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "女衫",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "湖上水",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "水衫",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "湖上雪",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "雪衫",
        	"quest_location":	"千金楼",
                "quest_type":           "寻",
                "exp_bonus":            71,
        ]),
        ([      "quest":                "馄饨",
        	"quest_location":	"华山",
                "quest_type":           "寻",
                "exp_bonus":            71,
        ]),
//end 71k
	([      "quest":                "玻璃弹子",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            78,
        ]),        
        ([      "quest":                "程小小",
                "quest_location":	"太平镇",
                "quest_type":           "杀",
                "exp_bonus":            78,
        ]), 
	([	"quest":		"当归",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
	([	"quest":		"剑南春酒袋",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
	([	"quest":		"面条",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
	([	"quest":		"芦苇",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
	([	"quest":		HIR"断肠草"NOR,
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
	([	"quest":		"黑玉发簪",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		78,
	]),
        ([	"quest":		GRN"莲蓬"NOR,
        	"quest_location":	"济南",
		"quest_type":		"寻",
                "exp_bonus":		80,
	]),
	([	"quest":		HIC"蓝色百褶裙"NOR,
		"quest_location":	"济南",
		"quest_type":		"寻",
                "exp_bonus":		80,
	]),
	([	"quest":		"清炒虾仁",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		80,
	]),
	([	"quest":		"脯雪黄鱼",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		80,
	]),
	([	"quest":		"排骨面",
		"quest_location":	"华山",
		"quest_type":		"寻",
                "exp_bonus":		80,
	]),
	([      "quest":                "旧鸟笼",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            80,
        ]),   
        ([      "quest":             "百灵鸟",
                "quest_location":	"昆仑山",
                "quest_type":           "杀",
                "exp_bonus":            80,
        ]),    
//end 80k
	([	"quest":		"陈皮大虾",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		85,
	]),
	([	"quest":		"果汁鱼球",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		85,
	]),
        ([      "quest":                "苏蓉蓉",
        	"quest_location":	"济南",
                "quest_type":           "杀",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "谢长勤",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "李长慎",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "供香",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "木棍",
                "quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "铁锤",
                "quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "小桃红",
                "quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            85,
        ]),        
        ([      "quest":                "粉红袄",
        	"quest_location":	"富贵山庄",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
        ([      "quest":                "鸡丁面",
        	"quest_location":	"华山",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
        ([	"quest":		"水玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		85,
	]),
 
	([	"quest":		"酒玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		85,
	]),
	([	"quest":		"花玉璧",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		85,
	]),
	([      "quest":                "捡破烂的",
                "quest_location":	"太平镇",
                "quest_type":           "杀",
                "exp_bonus":            85,
        ]), 
        ([      "quest":                "糌粑",
                "quest_location":	"藏北高原",
                "quest_type":           "寻",
                "exp_bonus":            85,
        ]),
//end 85k
        ([      "quest":                "干牛肉",
                "quest_location":	"藏北高原",
                "quest_type":           "寻",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "生仁鸡丁",
                "quest_location":	"边城",
                "quest_type":           "寻",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "清汤蹄子",
                "quest_location":	"边城",
                "quest_type":           "寻",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "武林大豪杰",
        	"quest_location":	"沉香镇",
                "quest_type":           "杀",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "老于头",
        	"quest_location":	"无名小镇",
                "quest_type":           "杀",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "金风",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            89,
        ]),
        ([      "quest":                "金雨",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            89, 
        ]),
	([	"quest":		"舍利子",
		"quest_location":	"关外",
		"quest_type":		"寻",
                "exp_bonus":		89,
	]),
	([	"quest":		"小锦鲤",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
		"exp_bonus":		89,
	]),
	([	"quest":		"大锦鲤",
		"quest_location":	"清平山庄",
		"quest_type":		"寻",
		"exp_bonus":		89,
	]),

//end 89k
        ([	"quest":		"云南白药",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		93,
	]),
        ([      "quest":                "三杯鳝段",
                "quest_location":	"边城",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "酒醉冬笋",
                "quest_location":	"边城",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "红烧排骨",
                "quest_location":	"边城",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "小喜鹊",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            93,
        ]), 
        ([      "quest":                BLK"黑郁金香"NOR,
        	"quest_location":	"南海",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "知客道人",
        	"quest_location":	"武当",
                "quest_type":           "杀",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "黄色道冠",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
        ([      "quest":                "青布道袍",
        	"quest_location":	"武当",
                "quest_type":           "寻",
                "exp_bonus":            93,
        ]),
// end 93k
        ([      "quest":                "黑冠巨蟒",
                "quest_location":	"新疆",
                "quest_type":           "杀",
                "exp_bonus":            93,
        ]),
	([	"quest":		"虎骨丸",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		100,
	]),
        ([      "quest":                "马小贝",
                "quest_location":	"二郎山",
                "quest_type":           "杀",
                "exp_bonus":            100,
                "difficulty":           50,
        ]), 
        ([      "quest":                "马小宝",
                "quest_location":	"二郎山",
                "quest_type":           "杀",
                "exp_bonus":            100,
                "difficulty":           50,
        ]), 
        ([      "quest":                "缺齿的钉耙",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            100,
        ]), 
        ([      "quest":                "金江",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]), 
        ([      "quest":                "金山",
        	"quest_location":	"富贵山庄",
                "quest_type":           "杀",
                "exp_bonus":            100,
        ]),  
	([	"quest":		"老和尚",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		100,
	]),
	([	"quest":		"白棉袈裟",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		100,
	]),
	([	"quest":		"南宫十三郎",
		"quest_location":	"沉香镇",
		"quest_type":		"杀",
		"exp_bonus":		100,
	]),
	([	"quest":		"红衣",
		"quest_location":	"幽灵山庄",
		"quest_type":		"寻",
                "exp_bonus":		100,
	]),
	([	"quest":		"百里灵",
		"quest_location":	"泰山",
		"quest_type":		"杀",
		"exp_bonus":		100,
	]),
	([	"quest":		"宋中",
		"quest_location":	"泰山",
		"quest_type":		"杀",
		"exp_bonus":		100,
	]),
	([	"quest":		"青年樵夫",
		"quest_location":	"华山",
		"quest_type":		"杀",
		"exp_bonus":		100,
	]),
// end 100k
	([	"quest":		"大风丸",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		105,
	]),
	([	"quest":		"煮熟了的蛆",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		105,
	]),
        ([      "quest":                "波斯奴",
        	"quest_location":	"关外",
                "quest_type":           "杀",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "弯刀",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "大红布袍",
        	"quest_location":	"关外",
                "quest_type":           "寻",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "护山使者",
        	"quest_location":	"三清宫",
                "quest_type":           "杀",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "桃木剑",
        	"quest_location":	"三清宫",
                "quest_type":           "寻",
                "exp_bonus":            105,
        ]),
        ([      "quest":                "大胡子",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            105,
        ]),
	([	"quest":		"精致鸟笼",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		105,
	]),
	([	"quest":		"乳香鲳鱼",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		105,
	]),
//end 105k
        ([      "quest":                "黑色的圆饼",
                "quest_location":	"太平镇",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]), 
        ([      "quest":                "牦牛",
                "quest_location":	"藏北高原",
                "quest_type":           "杀",
                "exp_bonus":            110,
        ]), 
        ([      "quest":                "灰老鼠",
                "quest_location":	"太平镇",
                "quest_type":           "杀",
                "exp_bonus":            110,
        ]), 
        ([      "quest":                "白老鼠",
                 "quest_location":	"太平镇",
                "quest_type":           "杀",
                "exp_bonus":            110,
        ]), 
        ([      "quest":                "钩连枪",
        	"quest_location":	"南海",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]),
        ([      "quest":                BLK"黑郁金香"NOR,
        	"quest_location":	"南海",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]),
	([	"quest":		"古松琴",
		"quest_location":	"兴国禅寺",
		"quest_type":		"寻",
		"exp_bonus":		110,
	]),
	([	"quest":		"李豹",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		110,
	]),
        ([      "quest":                "镖师",
        	"quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "石锁",
        	"quest_location":	"风云城",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]),
        ([      "quest":                "游客",
        	"quest_location":	"黄山或乌拉泊",
                "quest_type":           "杀",
                "exp_bonus":            110,
        ]),
        ([      "quest":                WHT"黄山风景图"NOR,
        	"quest_location":	"黄山",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]),
	([	"quest":		"金丝雀",
		"quest_location":	"万梅山庄",
		"quest_type":		"杀",
		"exp_bonus":		110,
	]),
	([	"quest":		"清炒虾仁",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		110,
	]),
        ([      "quest":                "白煮鸡蛋",
        	"quest_location":	"南海",
                "quest_type":           "寻",
                "exp_bonus":            110,
        ]),
//end 110k
	([	"quest":		"翠玉琵琶",
		"quest_location":	"千金楼",
		"quest_type":		"寻",
                "exp_bonus":		120,
	]),
	([	"quest":		"叶羽",
		"quest_location":	"白云",
		"quest_type":		"杀",
                "exp_bonus":		120,
	]),
        ([      "quest":                "阿福",
        	"quest_location":	"清平山庄",
                "quest_type":           "杀",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "巨型犬",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "刘老农",
        	"quest_location":	"黑松堡",
                "quest_type":           "杀",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "霍英",
        	"quest_location":	"黄山",
                "quest_type":           "杀",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "杜吟",
        	"quest_location":	"黄山",
                "quest_type":           "杀",
                "exp_bonus":            120,
        ]),
        ([      "quest":                "脚行僧",
                "quest_type":           "杀",
                "quest_location":	"华山",
                "exp_bonus":            120,
        ]),
	([	"quest":		"阿依古丽",
		"quest_location":	"新疆",
		"quest_type":		"杀",
		"exp_bonus":		120,
	]),
	([	"quest":		"紫金葫芦",
		"quest_location":	"帝王谷",
		"quest_type":		"寻",
                "exp_bonus":		120,
	]),
	([	"quest":		"艾绒",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		120,
	]),
	([	"quest":		RED"野果"NOR,
		"quest_location":	"狼山",
		"quest_type":		"寻",
                "exp_bonus":		120,
	]),
//end 120k
        ([	"quest":		"红油鸡片",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),
        ([	"quest":		"橄榄鱼翅",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),	
        ([	"quest":		"清炒鳝糊",
		"quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),	
        ([      "quest":                "岳洋",
        	"quest_location":	"南海",
                "quest_type":           "杀",
                "exp_bonus":            130,
        ]),
	([	"quest":		"虎骨",
		"quest_location":	"狼山",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),
	([	"quest":		BLK"黑靴"NOR,
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),
	([	"quest":		BLK"黑纱"NOR,
		"quest_location":	"大漠风沙",
		"quest_type":		"寻",
                "exp_bonus":		130,
	]),
        ([      "quest":                "劲装少年",
        	"quest_location":	"清平山庄",
                "quest_type":           "杀",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "公孙不智",
        	"quest_location":	"清平山庄",
                "quest_type":           "杀",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "青衣少女",
        	"quest_location":	"大旗谷",
                "quest_type":           "杀",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "青带",
        	"quest_location":	"大旗谷",
                "quest_type":           "寻",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "青衣",
        	"quest_location":	"大旗谷",
                "quest_type":           "寻",
                "exp_bonus":            132,
        ]),
        ([      "quest":                "落花",
        	"quest_location":	"狼山",
                "quest_type":           "寻",
                "exp_bonus":            132,
        ]),        
// end 132k
      ([      "quest":                "落花",
                "quest_location":	"狼山",
                "quest_type":           "寻",
                "exp_bonus":            145,
        ]),        
	([	"quest":		HIC"七"HIB"彩"HIG"海"HIY"螺"NOR,
                "quest_location":	"狼山",
		"quest_type":		"寻",
                "exp_bonus":		145,
	]),
        ([      "quest":                "大胡子豪客",
        	"quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "读千里",
                "quest_location":	"风云城",
                "quest_type":           "杀",
                "exp_bonus":            145,
        ]),
        ([      "quest":                "大胡子豪客",
                "quest_location":	"千金楼",
                "quest_type":           "杀",
                "exp_bonus":            145,
        ]),
//	end 145k        
	([	"quest":		"黑瓷药瓮",
                "quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		150,
	]),
	([	"quest":		"生烧扒翅",
                "quest_location":	"风云城",
		"quest_type":		"寻",
                "exp_bonus":		150,
	]),	
	([	"quest":		"铜佛鼓",
                "quest_location":	"千佛山",
		"quest_type":		"寻",
                "exp_bonus":		150,
	]),
	([	"quest":		"铁坎",
                "quest_location":	"狼山",
		"quest_type":		"杀",
		"exp_bonus":		150,
	]),
	([	"quest":		"铁力",
                "quest_location":	"狼山",
		"quest_type":		"杀",
		"exp_bonus":		150,
	]),
	([	"quest":		"黑瓷药瓮",
		"quest_location":	"沉香镇",
		"quest_type":		"寻",
                "exp_bonus":		150,
	]),
	([	"quest":		"铜佛鼓",
		"quest_location":	"兴国禅寺",
		"quest_type":		"寻",
                "exp_bonus":		150,
	]),
	([	"quest":		"铁坎",
		"quest_location":	"狼山",
		"quest_type":		"杀",
		"exp_bonus":		150,
	]),
	([	"quest":		"铁力",
		"quest_location":	"狼山",
		"quest_type":		"杀",
		"exp_bonus":		150,
	]),
	([	"quest":		"老樵夫",
		"quest_location":	"华山",
		"quest_type":		"杀",
		"exp_bonus":		150,
	]),
//end 150k
});
        

//Find the First Index to have exp level >= x
int Find(int x)
{
	int total;
	int low,high,now;
	total=sizeof(quest);
	if(quest[0]["exp_bonus"]>=x)
		return 0;
	if(quest[total-1]["exp_bonus"]<x)
		return total-1;

	low=0;
	high=total-1;
	now=(low+high)/2;

	while(high-low>1) {
		if(quest[now]["exp_bonus"]>=x)
			high=now;
		else 
   			low=now;
		now=(low+high)/2;
	}
	return high;
}

mapping query_quest(int exp)
{
	int a,b,c; 
	int low,high;
	
	if (exp > 7500) {		// (7.5M+)  [-800k, +500k];
		low = exp - 800;
		high = exp + 500;	
	} else if (exp > 5000) {	// (5M- 7.5M) [-500k, +400k]	
		low = exp - 400;
		high = exp + 300;	
	} else if(exp>1000) {		// (1M - 5M) [-400k, + 300k]
		low = exp - 300; 
		high = exp + 200;
	} else if (exp>750) {		//  (750k-1M) [0.8,1.2] 
		low=exp*8/10;
		high=exp*11/10;
	} else if (exp > 500) {		//  (500k-750k) [0.7,1.3]
		low=exp*7/10;
		high=exp*11/10;
	} else if (exp >8) {				//  (8-500k) [0.6,1.4] L1 之前 no faraway quest
		low = exp * 6/10;
		high = exp *11/10;
	} else {
		low = exp* 6/10;
		high = exp; 	
	} 
	
	if( low>12000) low=12000;  

	if(high<3) high=3;

	a=Find(low);
	b=Find(high)-1;
	c=a+random(b+1-a);
	return quest[c];
}

int TotalNumber()
{
	return sizeof(quest);
}

int KillNumber()
{
	int count=0;
	int i,total;
	total=sizeof(quest);
	for(i=0;i<total;i++) {
		if (quest[i]["quest_type"]=="杀") count++;
	}
	return count;
}

/*
int left_quest(){
	int num,num2,i,j, gotit;
	
	num = sizeof(quest2);
	num2 = sizeof(quest);
	for (i=0;i<num;i++){
		gotit = 0;
		for(j=0;j<num2;j++) {
		 	if (quest2[i]["quest"] == quest[j]["quest"]) {
		 		gotit=1; 
		 		break;
		 	}
		}
		if  (!gotit)
			write("extra quest = "+ quest2[i]["quest"] + " " +quest2[i]["exp_bonus"]+"\n");
	}
	return 1;
}*/
