/*  OK, we need three ranges of SMART_NPCs,

(1) NPC_BAS, 
	0-5M,  menpai skill only, Can have defense-parry, 
(2) NPC_MID, 
	5-10M  + all free-master skills and couple skill. 
	random_allowed in (5-15M);
(3) NPC_ADV, 
	10-15M + advanced basic, + haste/double, + adv-perk. 

		中级NPC
	
	此NPCLIST和相应的do_choose_attack_2 用以处理中级的NPC引用，
	比原来的NPC要强，有优化，强弱由chat_combat_chance决定。
	对一般NPC建议设置在30以下
	你也可以只引用auto_setup设置而不引用Smart_fight.
	
	0-5M 此表共计63个NPC，1个random NPC。

	* 明月增加了9个魔教NPC，因为使用rascal skill，不进入random list
	
	------- by Silencer@fy4 workgroup 3/20/2003
	
*/

inherit SKILL;

string weapon_unarmed(string weapon_i,string unarmed_i);
int check_health(object target, int percent);
int accompany(object me);
int is_he_pet(object target);
int enemy_type(object enemy);
object *resort_enemy(string flag);
object *resort(object *group);

mapping *npctype = ({
//	随机的小喽罗。打法ok但并非优化。	
// This will generate a random skill NPC. Do not specify his weapon since he uses varies skills.
// He has some dodge/unarmed busy and a weapon attaack, difficulty moderate I would say.
// You can use it as 小喽罗.
	([      
		"group":		"fighter_w",
		"npc":                	"smallguy",
                "name":			"小喽罗",
                "class":	      	"wolfmount",
                "gender":		"男性",
                "force":		"manjianghong",
		"others1":		"bloodystrike",
		"others2":		"strategy",
		"others3":		"leadership",
		"perform_weapon_attack": "random",
		"perform_unarmed_attack":"random",
		"perform_busy_d":	 "random",
		"perform_busy_u":	 "random",
        ]),
//	铁雪
	([      
		"group":		"fighter_w",
		"npc":                	"diesword",
                "name":			"蝶舞",
                "class":	     "legend",
                "gender":		"女性",
                "skill_type_w":	 "sword/diesword",
                "skill_type_u":	"qidaoforce",
                "skill_type_d":	"fall-steps",
                "unarmed":		"qidaoforce",
                "sword":		"diesword",
                "force":		"qidaoforce",
                "parry":		"diesword",
                "blade":		"shortsong-blade",
                "dodge":		"fall-steps",
				"others1":		"meihua-shou",
				"others2":		"six-sense",
				"perform_weapon_attack":"legend/sword/diesword/caidiekuangwu",
				"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
				"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",      
				"set_master":		"master xuerui",          
        ]),  
        ([      
		"group":		"fighter_w",
		"npc":                	"shortsong-blade",
                "name":			"阿谈",
                "class":	      	"legend",
                "gender":		"男性",
                "skill_type_w":	      	"blade/shortsong-blade",
                "skill_type_u":		"qidaoforce",
                "skill_type_d":		"fall-steps",
                "unarmed":		"qidaoforce",
                "blade":		"shortsong-blade",
                "force":		"qidaoforce",
                "parry":		"shortsong-blade",
                "dodge":		"fall-steps",
                "others1":		"meihua-shou",
		"perform_weapon_attack":"legend/blade/shortsong-blade/duangechangmeng",
		"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",
		"set_temp1":		"pfm/qidaoforce_juqi",           
        ]),  
//	丐帮       
	([      // this exists only for compatibility reason, same as dagou-stick1
		"group":		"fighter_w",
		"npc":                	"dagou-stick",
                "name":			"上官十",
                "class":	      	"beggar",
                "gender":		"男性",
                "skill_type_w":	    "staff/dagou-stick",
                "skill_type_u":		"dragonstrike",
                "skill_type_d":		"doggiesteps",
                "unarmed":		"dragonstrike",
                "staff":		"dagou-stick",
                "force":		"huntunforce",
                "parry":		"dagou-stick",
                "dodge":		"doggiesteps",
                "others1":		"begging",
                "perform_weapon_attack":"beggar/staff/dagou-stick/tianxiawugou",
				"perform_weapon_attack2":"beggar/staff/dagou-stick/chuozijue",
				"perform_unarmed_attack":"beggar/unarmed/dragonstrike/xianglongwuhui",
                "perform_unarmed_attack2":"beggar/unarmed/dragonstrike/shichengliulong",
                "perform_unarmed_attack3":"beggar/unarmed/dragonstrike/zhenjingbaili",	

        ]),   
        	([      		// 60
		"group":		"fighter_w",
		"npc":                	"dagou-stick1",
                "name":			"上官十",
                "class":	      	"beggar",
                "gender":		"男性",
                "skill_type_w":	    "staff/dagou-stick",
                "skill_type_u":		"dragonstrike",
                "skill_type_d":		"doggiesteps",
                "unarmed":		"dragonstrike",
                "staff":		"dagou-stick",
                "force":		"huntunforce",
                "parry":		"dagou-stick",
                "dodge":		"doggiesteps",
                "others1":		"begging",
                "perform_weapon_attack":"beggar/staff/dagou-stick/tianxiawugou",
				"perform_weapon_attack2":"beggar/staff/dagou-stick/chuozijue",
				"perform_unarmed_attack":"beggar/unarmed/dragonstrike/xianglongwuhui",
                "perform_unarmed_attack2":"beggar/unarmed/dragonstrike/shichengliulong",
                "perform_unarmed_attack3":"beggar/unarmed/dragonstrike/zhenjingbaili",	

        ]), 
// 金钱 
        ([    
        	"group":		"fighter_w",
		"npc":                	"longfenghuan",
                "name":			"云",
                "class":	      	"assassin",
                "gender":		"男性",
                "skill_type_w":	      	"hammer/longfenghuan",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "d_adjust":		50,
                "unarmed":		"flame-strike",
                "hammer":		"longfenghuan",
                "force":		"jingxing",
                "parry":		"longfenghuan",
                "dodge":		"jinhong-steps",
                "sword":		"sharen-sword",
                "others1":		"bloodystrike",
                "perform_weapon_attack":"assassin/hammer/longfenghuan/longfengshuangfei",
				"perform_weapon_attack2":"assassin/sword/sharen-sword/sharenruma",
				"perform_unarmed_attack":"assassin/dodge/jinhong-steps/canglongzhaxian",
        ]),  
        ([    
        	"group":		"fighter_w",
		"npc":                	"longfenghuan1",
                "name":			"云",
                "class":	      	"assassin",
                "gender":		"男性",
                "skill_type_w":	      	"hammer/longfenghuan",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "d_adjust":		50,
                "unarmed":		"flame-strike",
                "hammer":		"longfenghuan",
                "force":		"jingxing",
                "parry":		"longfenghuan",
                "dodge":		"jinhong-steps",
                "others1":		"bloodystrike",
                "perform_weapon_attack":"assassin/hammer/longfenghuan/longfengshuangfei",
				"perform_busy_d":	"random",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]),  
        ([    
        	"group":		"fighter_w",
		"npc":                	"sharen-sword",
                "name":			"小飞",
                "class":	      	"assassin",
                "gender":		"男性",
                "skill_type_w":	      	"sword/sharen-sword",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "d_adjust":		50,
                "unarmed":		"flame-strike",
                "sword":		"sharen-sword",
                "force":		"jingxing",
                "parry":		"lefthand-sword",
                "dodge":		"jinhong-steps",
                "others1":		"lefthand-sword",
		"perform_weapon_attack":"assassin/sword/sharen-sword/sharenruma",
		"perform_busy_d":	"random",
		"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]),  
        ([    
        	"group":		"fighter_w",
		"npc":                	"mapo",
                "name":			"冰冻",
                "class":	      	"assassin",
                "gender":		"男性",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "unarmed":		"flame-strike",
                "force":		"jingxing",
                "parry":		"longfenghuan",
                "dodge":		"jinhong-steps",
                "iron-cloth":		"xisui",
                "spells":		"mapo",
        ]),  
//	神水
		([ 	
		"group":		"fighter_w",
		"npc":                	"nine-moon-sword",
                "name":			"明月",
                "class":	      	"shenshui",
                "gender":		"女性",
                "skill_type_w":	      	"sword/nine-moon-sword",
                "skill_type_u":		"nine-moon-claw",
                "skill_type_d":		"nine-moon-steps",
                "unarmed":		"nine-moon-claw",
                "sword":		"nine-moon-sword",
                "force":		"nine-moon-force",
                "parry":		"nine-moon-sword",
                "dodge":		"nine-moon-steps",
		"others1":		"nine-moon-spirit",
		"others2":		"qingpingsword",
		"perform_weapon_attack":"shenshui/sword/nine-moon-sword/shuanglengcanxia",
		"perform_unarmed_attack":"shenshui/unarmed/nine-moon-claw/polu",
		"perform_busy_w":	"shenshui/sword/nine-moon-sword/yanduhantan",
		"set_temp1":		"nine-moon-force_poison",           
        ]), 
 
//	帝王谷  	
  	([      
		"group":		"fighter_w",
		"npc":                	"thunderwhip",
                "name":			"小狂刀",
                "class":	      	"yinshi",
                "gender":		"男性",
                "skill_type_w":	      	"whip/thunderwhip",
                "skill_type_u":		"flying-dragon",
                "skill_type_d":		"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "force":		"iceheart",
                "parry":		"thunderwhip",
                "dodge":		"zuixian-steps",
                "whip":			"thunderwhip",
				"cursism":		"celecurse",
				"others1":		"liangyi-force",
				"others2":		"qiankunwuxing",
		"perform_weapon_attack":"yinshi/whip/thunderwhip/yunlongjiuxian",
		"perform_unarmed_attack":"yinshi/unarmed/flying-dragon/longwujiutian",
        "perform_buff_1":"yinshi/cursism/celecurse/boostcurse",
        "perform_buff_2":"yinshi/dodge/zuixian-steps/baxianzuijiu",        
        ]),
          	([      
		"group":		"fighter_w",
		"npc":                	"pangu-hammer",
                "name":			"小狂刀",
                "class":	      	"yinshi",
                "gender":		"男性",
                "skill_type_w":	    "hammer/pangu-hammer",
                "skill_type_u":		"pofeng-strike",
                "skill_type_d":		"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "hammer":		"pangu-hammer",
                "force":		"liangyi-force",
                "parry":		"pangu-hammer",
                "dodge":		"zuixian-steps",
                "whip":			"thunderwhip",
                "cursism":		"celecurse",
		"perform_weapon_attack":"yinshi/hammer/pangu-hammer/kaitianpidi",
		"perform_unarmed_attack":"yinshi/unarmed/pofeng-strike/luanpofeng",
		"perform_busy_u":"yinshi/unarmed/pofeng-strike/rufengsibi",
        "perform_buff_1":"yinshi/cursism/celecurse/boostcurse",
        "perform_buff_2":"yinshi/dodge/zuixian-steps/baxianzuijiu",
        ]),
//	华山 。。。。 
	([      
		"group":		"fighter_w",
		"npc":         	"tanzhi-shentong",
                "name":			"深红月光",
                "class":	     "huashan",
                "gender":		"女性",
                "skill_type_w":	 "throwing/tanzhi-shentong",
                "skill_type_u":	"zhaixin-claw",
                "skill_type_d":	"cloud-dance",
                "unarmed":		"zhaixin-claw",
                "force":		"hanmei-force",
                "dodge":		"cloud-dance",
                "parry":		"tanzhi-shentong",
                "throwing":		"tanzhi-shentong",
				"iron-cloth":	"spring-water",
				"perform_weapon_attack":  "huashan/throwing/tanzhi-shentong/mantianhuayu",
				"perform_weapon_attack2": "huashan/throwing/tanzhi-shentong/xinyouqianjie",
				"perform_busy_u":       "huashan/throwing/tanzhi-shentong/tanzhijinghun",
				"perform_busy_d":       "huashan/dodge/cloud-dance/yexuechuji",
        ]),
        ([      
		"group":		"fighter_w",
		"npc":                	"qingfeng-sword",
                "name":			"深蓝月光",
                "class":	     "huashan",
                "gender":		"女性",
                "skill_type_w":	 "sword/qingfeng-sword",
                "skill_type_u":	"zhaixin-claw",
                "skill_type_d":	"cloud-dance",
                "unarmed":		"zhaixin-claw",
                "sword":		"qingfeng-sword",
                "force":		"hanmei-force",
                "parry":		"qingfeng-sword",
                "dodge":		"cloud-dance",
				"iron-cloth":		"spring-water",
				"perform_unarmed_attack":"huashan/force/hanmei-force/chill",
				"perform_busy_d":       "huashan/dodge/cloud-dance/yexuechuji",
        ]), 
//	武当        
	([      
		"group":		"fighter_w",
		"npc":                	"taiji-sword",
                "name":			"蝴蝶",
                "class":	      	"wudang",
                "gender":		"女性",
                "skill_type_w":	      	"sword/taiji-sword",
                "skill_type_u":		"taiji",
                "w_adjust":		0,
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "sword":		"taiji-sword",
                "force":		"taijiforce",
                "parry":		"taiji-sword",
                "dodge":		"five-steps",
                "others1":		"enmeiryu",
                "iron-cloth":		"xisui",
		"perform_busy_w":	"wudang/sword/taiji-sword/chanzijue",
		"perform_unarmed_attack":"ninja/unarmed/enmeiryu/mukuha",        
		"perform_unarmed_attack2":"ninja/unarmed/enmeiryu/shimon",
        ]), 
	([      
		"group":		"fighter_w",
		"npc":                	"taiji",
                "name":			"阿龙",
                "class":	      	"wudang",
                "gender":		"男性",
                "skill_type_w":	      	"sword/taiji-sword",
                "skill_type_u":		"taiji",
                "w_adjust":		0,
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "force":		"taijiforce",
                "sword":		"taiji-sword",
                "parry":		"taiji-sword",
                "dodge":		"five-steps",
                "iron-cloth":		"xisui",
                "others1":		"enmeiryu",
		"perform_busy_u":	"wudang/unarmed/taiji/nianzijue",
		"perform_unarmed_attack":"ninja/unarmed/enmeiryu/mukuha",        
		"perform_unarmed_attack2":"ninja/unarmed/enmeiryu/shimon",
		"perform_unarmed_attack3":"wudang/unarmed/taiji/nianzijue",
        ]), 
//	万梅，
	([      
		"group":		"fighter_w",
		"npc":                	"doomsword",
                "name":			"东门飞雪",
                "class":	      	"fighter",
                "gender":		"女性",
                "skill_type_w":	      	"sword/doomsword",
                "skill_type_u":		"doomstrike",
                "skill_type_d":		"doomsteps",
                "unarmed":		"doomstrike",
                "sword":		"doomsword",
                "force":		"doomforce",
                "parry":		"doomsword",
                "dodge":		"doomsteps",
		"others1":		"meihua-shou",
		"perform_weapon_attack":"fighter/sword/doomsword/hunranyijian",
		"perform_unarmed_attack":"fighter/unarmed/doomstrike/hantian",
		"perform_busy_u":"legend/unarmed/meihua-shou/meihai",
        ]), 
//	富贵山庄。
 	([      
		"group":		"fighter_w",
		"npc":                	"xuezhan-spear",
                "name":			"阿铭",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_w":	      	"spear/xuezhan-spear",
                "skill_type_u":		"eagle-claw",
                "u_adjust":		 20,
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
		"iron-cloth":		"henglian",
		"others1":		"yue-spear",
		"others2":		"manjianghong",
		"perform_weapon_attack":"fugui/spear/xuezhan-spear/yutianbigao",
		"perform_weapon_attack2":"fugui/spear/xuezhan-spear/bafangfengyu",
		"perform_weapon_attack3":"official/spear/yue-spear/zonghengtianxia",
		"perform_busy_d":       "fugui/dodge/hawk-steps/yingjichangkong",
        ]),
        ([      // This is a good example of FUGUI fighting... quite deadly, need 100 chance to showoff
		"group":		"fighter_w",
		"npc":                	"xuezhan-spear2",
                "name":			"阿铭",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_w":	   "spear/xuezhan-spear",
                "skill_type_u":		"eagle-claw",
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
				"iron-cloth":		"henglian",
				"perform_weapon_attack":"fugui/spear/xuezhan-spear/jinshiweikai",
				"perform_weapon_attack2":"fugui/spear/xuezhan-spear/bafangfengyu",
				"perform_weapon_attack3":"fugui/spear/xuezhan-spear/liguangsheshi",
				"perform_weapon_attack4":"fugui/spear/xuezhan-spear/xueyuxiaoxiao",	
				"perform_busy_w":       "fugui/spear/xuezhan-spear/wulongbaiwei",
				"perform_unarmed_attack": "fugui/unarmed/eagle-claw/cunjin",
        ]),              
//	兴国
	([      
		"group":		"fighter_w",
		"npc":                	"cloudstaff",
                "name":			"苦苦",
                "class":	      	"bonze",
                "gender":		"男性",
                "skill_type_w":	      	"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"nodust-steps",
				"magic":		"essencemagic",
				"perform_weapon_attack":"bonze/staff/cloudstaff/longxianyuye",
				"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
        ]), 
	([      
		"group":		"fighter_w",
		"npc":                	"mind-sense",
                "name":			"笨笨",
                "class":	      	"bonze",
                "gender":		"男性",
                "skill_type_w":	      	"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"nodust-steps",
				"magic":		"essencemagic",
				"perform_unarmed_attack":"bonze/magic/essencemagic/mind_sense",
				"perform_unarmed_attack2":"bonze/magic/essencemagic/light_sense",
				"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
      ]), 
//	神机和蝙蝠
//Shenji-blade && bat-blade
        ([      
		"group":		"fighter_w",
		"npc":                	"shenji-blade",
                "name":			"谢老掌柜",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_w":	    "blade/shenji-blade",
                "skill_type_u":		"luoriquan",
                "skill_type_d":		"shenji-steps",
                "unarmed":		"luoriquan",
                "blade":		"shenji-blade",
                "parry":		"shenji-blade",
                "dodge":		"shenji-steps",
				"others1":		"wind-blade",
		"perform_weapon_attack":"npc/blade/shenji-blade/jichulianhuan",
		"perform_weapon_attack2":"npc/blade/wind-blade/leitingpili",
		"perform_unarmed_attack":"bat/unarmed/luoriquan/luori",
		"perform_unarmed_attack2":"bat/unarmed/luoriquan/changrijiangjin",
		"perform_busy_d":       "npc/dodge/shenji-steps/shenjimiaosuan",
        ]), 
        ([      
		"group":		"fighter_w",
		"npc":                	"bat-blade",
                "name":			"袁青谷",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_w":	      	"blade/bat-blade",
                "skill_type_u":		"luoriquan",
                "skill_type_d":		"meng-steps",
                "unarmed":		"luoriquan",
                "blade":		"bat-blade",
                "parry":		"bat-blade",
                "force":		"wuzheng-force",
                "dodge":		"meng-steps",
                "others2":		"wind-blade",
		"perform_weapon_attack":"bat/blade/bat-blade/shiwanshenmo",
		"perform_weapon_attack2":"npc/blade/wind-blade/leitingpili",
		"perform_unarmed_attack":"bat/unarmed/luoriquan/luori",
		"perform_unarmed_attack2":"bat/unarmed/luoriquan/changrijiangjin",	
		"perform_busy_d":       "bat/dodge/meng-steps/huanyinqianchong",
        ]), 
//	魔教
	([      
		"group":		"fighter_w",
		"npc":         	"demon-blade",
                "name":			"天",
                "class":	      	"demon",
                "gender":		"男性",
                "skill_type_w":		"blade/demon-blade",
                "skill_type_u":		"demon-strike",
                "skill_type_d":		"demon-steps",
                "unarmed":		"demon-strike",
                 "dodge":		"demon-steps",
                 "parry":		"demon-blade",
                 "blade":		"demon-blade",
                 "force":		"demon-force",
                "perform_weapon_attack": "demon/blade/demon-blade/tiandirenmo",
                "perform_unarmed_attack":"demon/unarmed/demon-strike/tianmo",
                "perform_unarmed_attack2":"demon/unarmed/demon-strike/dimo",
                "perform_unarmed_attack3":"demon/unarmed/demon-strike/renmo",
				"perform_busy_d":       "demon/dodge/demon-steps/lianhuanbabu",
        ]),
	([      
		"group":		"fighter_w",
		"npc":                	"demon-strike",
                "name":			"天",
                "class":	      	"demon",
                "gender":		"男性",
                "skill_type_u":		"demon-strike",
                "skill_type_d":		"demon-steps",
                "unarmed":		"demon-strike",
                 "dodge":		"demon-steps",
                 "force":		"demon-force",
                "perform_unarmed_attack":"demon/unarmed/demon-strike/tianmo",
                "perform_unarmed_attack2":"demon/unarmed/demon-strike/dimo",
                "perform_unarmed_attack3":"demon/unarmed/demon-strike/renmo",
		"perform_busy_d":       "demon/dodge/demon-steps/lianhuanbabu",
        ]),         
                
//	神剑
	([      
		"group":		"fighter_w",
		"npc":                	"softsword",
                "name":			"天意梦断",
                "class":	      	"swordsman",
                "gender":		"男性",
                "skill_type_w":	      	"sword/softsword",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"shadowsteps",
                "unarmed":		"dabei-strike",
                "sword":		"softsword",
                "force":		"cloudforce",
                "iron-cloth":		"xisui",
                "parry":		"softsword",
                "dodge":		"shadowsteps",
		"perform_weapon_attack":"swordsman/sword/softsword/npc_sword_muyu",
		"perform_weapon_attack2":"swordsman/sword/softsword/changtianluodian",
		"perform_unarmed_attack":"swordsman/dodge/shadowsteps/lianhuanjiao",
		"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]), 
//	少林
  	([  	// This one will auto clone weapon if not setup  
		"group":		"fighter_w",
		"npc":                	"wuche-axe",
                "name":			"马休",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	      	"axe/wuche-axe",
                "skill_type_u":		"yijinjing",
                "skill_type_d":		"puti-steps",
                "unarmed":		"yijinjing",
                "axe":			"wuche-axe",
                "hammer":		"liuxing-hammer",
                "force":		"xiaochengforce",
                "parry":		"wuche-axe",
                "dodge":		"puti-steps",
                "spear":		"duanhun-spear",
                "staff":		"fumostaff",
		"iron-cloth":		"yijinjing",
		"others1":		"dabei-strike",
		"others2":		"yiyangzhi",
		"others3":		"tenderzhi",
		"perform_weapon_attack":"shaolin/axe/wuche-axe/sanbanfu",
		"perform_weapon_attack2":"shaolin/hammer/liuxing-hammer/fanbei",
		"perform_weapon_attack3":"shaolin/spear/duanhun-spear/suomengchanhun",
		"perform_unarmed_attack":"shaolin/unarmed/yiyangzhi/qiankun",
		"perform_unarmed_attack2":"taoist/unarmed/tenderzhi/qiankun",
		"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
		"perform_busy_w":"shaolin/staff/fumostaff/hequhecong",
		"perform_buff_1":"shaolin/dodge/puti-steps/wuwuwuwo",  
        ]),     
  	([  	// chant and yijinjing are same    
		"group":		"fighter_u",
		"npc":                	"chant",
                "name":			"小强",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_u":		"yizhichan",
                "skill_type_d":		"puti-steps",
                "unarmed":		"yizhichan",
                "force":		"yijinjing",
                "dodge":		"puti-steps",
				"iron-cloth":		"yijinjing",
				"others1":			"dabei-strike",
				"others2":			"buddhism",
				"others3":			"lamaism",
				"others4":			"zen",
		"perform_unarmed_attack":"shaolin/unarmed/yizhichan/nianhua",
		"perform_buff_1":	"shaolin/dodge/puti-steps/wuwuwuwo",
		"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),  
  	([      
		"group":		"fighter_u",
		"npc":                	"yijinjing",
                "name":			"小天意",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_u":		"yizhichan",
                "skill_type_d":		"puti-steps",
                "unarmed":		"yizhichan",
                "force":		"yijinjing",
                "dodge":		"puti-steps",
				"iron-cloth":		"yijinjing",
				"others1":			"dabei-strike",
				"others2":			"buddhism",
				"others3":			"lamaism",
				"others4":			"zen",
		"perform_unarmed_attack":"shaolin/unarmed/yizhichan/nianhua",
		"perform_buff_1":	"shaolin/dodge/puti-steps/wuwuwuwo",
		"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),  
//	天枫
	([      
		"group":		"fighter_w",
		"npc":                	"ittouryu",
                "name":			"恶鬼",
                "class":	      	"ninja",
                "gender":		"女性",
                "skill_type_w":	      	"blade/ittouryu",
                "skill_type_u":		"enmeiryu",
                "skill_type_d":		"ghosty-steps",
                "unarmed":		"enmeiryu",
                "blade":		"ittouryu",
                "force":		"ghosty-force",
                "parry":		"ittouryu",
                "dodge":		"ghosty-steps",
				"others2":		"wind-blade",
		"perform_weapon_attack":"ninja/blade/ittouryu/gobankiri",
		"perform_weapon_attack2":"npc/blade/wind-blade/leitingpili",
		"perform_weapon_attack3":"ninja/blade/ittouryu/hyakki",
		"perform_unarmed_attack":"ninja/unarmed/enmeiryu/shimon",
		"perform_unarmed_attack2":"ninja/unarmed/enmeiryu/mukuha",
        ]), 
//	官府
	([      
		"group":		"fighter_w",
		"npc":                	"yue-spear1",
                "name":			"无聊",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"fall-steps",
				"unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"fall-steps",
		"others1":		"bloodystrike",
		"others2":		"strategy",
		"others3":		"leadership",
		"perform_weapon_attack":"official/spear/yue-spear/zonghengtianxia",
		"perform_unarmed_attack": "random",
		"perform_unarmed_attack2":"official/unarmed/changquan/yuhuan",
		"perform_busy_d":	"random",
		"perform_busy_u":	"random",
	]),
	([      
		"group":		"fighter_w",
		"npc":                	"yue-spear1a",
                "name":			"无聊",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"fall-steps",
				"unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"fall-steps",
		"others1":		"bloodystrike",
		"others2":		"strategy",
		"others3":		"leadership",
		"perform_weapon_attack":"official/spear/yue-spear/zonghengtianxia",
		"perform_unarmed_attack": "random",
		"perform_unarmed_attack2":"official/unarmed/changquan/yuhuan",
		"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]),
	([      // basically same as 2a
		"group":		"fighter_w",
		"npc":                	"yue-spear2",
                "name":			"土土",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"puti-steps",
                "unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"puti-steps",
				"others2":		"strategy",
				"others3":		"leadership",
		"perform_weapon_attack":	"official/spear/yue-spear/zonghengtianxia",
		"perform_unarmed_attack":	"official/unarmed/changquan/yuhuan",
		"set_master":		"master yue",
		"perform_buff_1":"shaolin/dodge/puti-steps/wuwuwuwo",  
        ]),   
        	([      
		"group":		"fighter_w",
		"npc":                	"yue-spear2a",
                "name":			"土土",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"puti-steps",
                "unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"puti-steps",
		"others2":		"strategy",
		"others3":		"leadership",
		"perform_weapon_attack":"official/spear/yue-spear/zonghengtianxia",
		"perform_unarmed_attack":"random",
		"set_master":		"master yue",
		"perform_buff_1":"shaolin/dodge/puti-steps/wuwuwuwo",  
        ]), 
//	狼山
	([      
		"group":		"fighter_w",
		"npc":                	"assassin-hammer",
                "name":			"搏浪",
                "class":	      	"wolfmount",
                "gender":		"男性",
                "skill_type_w":	      	"hammer/assassin-hammer",
                "skill_type_u":		"wolf-strike",
                "skill_type_d":		"xueyeqianzong",
                "unarmed":		"wolf-strike",
                "hammer":		"assassin-hammer",
                "force":		"wolf-force",
                "parry":		"assassin-hammer",
                "dodge":		"xueyeqianzong",
                "cursism":		"wolf-curse",
				"others1":		"summonwolf",
				"perform_unarmed_attack":"wolfmount/unarmed/wolf-strike/shigu",
				"perform_unarmed_attack2":"wolfmount/unarmed/wolf-strike/canzhi",
				"perform_unarmed_attack3":"wolfmount/unarmed/wolf-strike/ningxue",	
				"perform_buff_1":"wolfmount/dodge/xueyeqianzong/wolverine",  
        ]), 
//  	大昭
	([      
		"group":		"fighter_w",
		"npc":                	"jin-gang",
                "name":			"雷芳",
                "class":	      	"lama",
                "gender":			"男性",
                "skill_type_w":	   	"staff/fengmo-staff",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"puti-steps",
                "unarmed":		"bloodystrike",
                "force":		"bolomiduo",
                "parry":		"fengmo-staff",
                "dodge":		"puti-steps",
                "staff":		"fengmo-staff",
                "spells":		"kwan-yin-spells",
				"iron-cloth":		"jin-gang",
		"perform_unarmed_attack":	"lama/unarmed/bloodystrike/yinqi",
		"perform_weapon_attack2":    "lama/staff/fengmo-staff/xianglong",
		"perform_weapon_attack":   "lama/staff/fengmo-staff/fuhu",	
        ]), 
  	([      
		"group":		"magician",
		"npc":                	"kwan-yin-spells",
                "name":			"雨飞",
                "class":	      	"lama",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"puti-steps",
                "unarmed":		"bloodystrike",
                "force":		"bolomiduo",
                "dodge":		"puti-steps",
                "spells":		"kwan-yin-spells",
				"iron-cloth":		"jin-gang",
				"iron-cloth":		"jin-gang",
		"perform_unarmed_attack":		"lama/spells/kwan-yin-spells/2word",
		"perform_unarmed_attack2":		"lama/spells/kwan-yin-spells/3word",					
        ]), 
//	三清
 	([      // the following 3 are same due to compatibility
		"group":		"magician",
		"npc":                	"necromancy",
                "name":			"阿蕊",
                "class":	      	"taoist",
                "gender":		"女性",
                "skill_type_w":	      	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "scratching":		"scratmancy",
                "others1":		"bloodystrike",
				"perform_weapon_attack":"taoist/sword/snowshade-sword/baixueaiai",
				"perform_unarmed_attack":"taoist/unarmed/tenderzhi/qiankun",
        		"perform_unarmed_attack2":"lama/unarmed/bloodystrike/fofawubian",
        		"perform_buff_1":"taoist/dodge/notracesnow/mantianfeixue", 
        ]), 
  	([      
		"group":		"magician",
		"npc":                	"scratmancy",
                "name":			"飞涛",
                "class":	      	"taoist",
                "gender":		"男性",
                "skill_type_w":	      	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "scratching":		"scratmancy",
                "others1":		"bloodystrike",
				"perform_weapon_attack":"taoist/sword/snowshade-sword/baixueaiai",
				"perform_unarmed_attack":"taoist/unarmed/tenderzhi/qiankun",
        		"perform_unarmed_attack2":"lama/unarmed/bloodystrike/fofawubian",
        		"perform_buff_1":"taoist/dodge/notracesnow/mantianfeixue", 
        ]),                                 
  	([      
		"group":		"magician",
		"npc":                	"alchemy",
                "name":			"催命道长",
                "class":	      	"taoist",
                "gender":		"男性",
                "skill_type_w":	      	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "scratching":		"scratmancy",
                "others1":		"bloodystrike",
				"perform_weapon_attack":"taoist/sword/snowshade-sword/baixueaiai",
				"perform_unarmed_attack":"taoist/unarmed/tenderzhi/qiankun",
        		"perform_unarmed_attack2":"lama/unarmed/bloodystrike/fofawubian",
        		"perform_buff_1":"taoist/dodge/notracesnow/mantianfeixue", 
        ]),    
//	快活林
	([      
		"group":		"fighter_w",
		"npc":                	"xuanyuan-axe",
                "name":			"大西瓜",
                "class":	      	"knight",
                "gender":		"男性",
                "skill_type_w":	      	"axe/xuanyuan-axe",
                "skill_type_u":		"hanshan-strike",
                "skill_type_d":		"windy-steps",
                "unarmed":		"hanshan-strike",
                "axe":			"xuanyuan-axe",
                "force":		"longlife-force",
                "parry":		"xuanyuan-axe",
                "dodge":		"windy-steps",
                "herb":			"dream-herb",
				"perform_weapon_attack":"knight/axe/xuanyuan-axe/guifushengong",
				"perform_weapon_attack2":"knight/axe/xuanyuan-axe/jiuqipoxiao",	
				"perform_weapon_attack3":"knight/axe/xuanyuan-axe/pangukaitian",			
				"perform_unarmed_attack": "knight/unarmed/hanshan-strike/zhangjian",
				"perform_busy_d":       "knight/herb/dream-herb/kaixiehua",
        ]), 
//	白云
        ([      
		"group":		"fighter_w",
		"npc":                	"musician",
                "name":			"琵琶公主",
                "class":	      	"baiyun",
                "gender":		"女性",
                "skill_type_w":	      	"sword/feixian-sword",
                "skill_type_u":		"calligraphy",
                "force":		"chessism",
		"unarmed":		"calligraphy",
                "sword":		"feixian-sword",
                "parry":		"feixian-sword",
                "dodge":		"feixian-steps",
                "others1":		"dabei-strike",
                "others2":		"fengyu-piaoxiang",
		"magic":		"music",
		"perform_weapon_attack":"baiyun/sword/feixian-sword/tianwaifeixian",
		"perform_unarmed_attack":"baiyun/unarmed/calligraphy/sangluan",
		"perform_busy_d":	"legend/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
        ]),	
//	黄山
	([      
		"group":		"fighter_w",
		"npc":                	"siqi-sword",
                "name":			"四奇",
                "class":	      	"huangshan",
                "gender":		"女性",
                "skill_type_w":	      	"sword/siqi-sword",
                "skill_type_u":		"yunwu-strike",
                "skill_type_d":		"liuquan-steps",
                "unarmed":		"yunwu-strike",
                "sword":		"siqi-sword",
                "force":		"xianjing",
                "parry":		"siqi-sword",
                "dodge":		"liuquan-steps",
		"perform_weapon_attack":"huangshan/sword/siqi-sword/siqi",
		"perform_busy_u":	"huangshan/unarmed/yunwu-strike/miwu",     
        ]), 
	([      
		"group":		"fighter_w",
		"npc":                	"qiusheng-blade",
                "name":			"秋声",
                "class":	      	"huangshan",
                "gender":		"男性",
                "skill_type_w":	      	"blade/qiusheng-blade",
                "skill_type_u":		"yunwu-strike",
                "skill_type_d":		"liuquan-steps",
                "unarmed":		"yunwu-strike",
                "blade":		"qiusheng-blade",
                "force":		"xianjing",
                "parry":		"qiusheng-blade",
                "dodge":		"liuquan-steps",
		"perform_weapon_attack":"huangshan/blade/qiusheng-blade/jingsheng",
		"perform_busy_u":	"huangshan/unarmed/yunwu-strike/miwu",     
        ]), 
//	BERSERKER
	// powerup-one
	([      
		"group":		"fighter_w",
		"npc":                	"spring-blade",
                "name":			"天涯",
                "class":	      	"berserker",
                "gender":		"女性",
                "skill_type_w":	      	"blade/spring-blade",
                "skill_type_u":		"venusfinger",
                "skill_type_d":		"xifengying",
				"d_adjust":			15,
                "unarmed":		"venusfinger",
                "blade":		"spring-blade",
                "force":		"gaunforce",
                "parry":		"spring-blade",
                "dodge":		"xifengying",
				"dagger":		"dug",
		"perform_weapon_attack":"berserker/blade/spring-blade/fengsiyunqi",
		"perform_weapon_attack2":"berserker/blade/spring-blade/obliterate",
		"perform_weapon_attack3":"berserker/dagger/dug/deathtouch",
		"perform_unarmed_attack":	"berserker/unarmed/venusfinger/panguaxe",     
        ]), 
	// forceup-one
	([      
		"group":		"fighter_w",
		"npc":                	"tempestsword",
                "name":			"长庚",
                "class":	      	"berserker",
                "gender":		"男性",
                "skill_type_w":	      	"sword/tempestsword",
                "skill_type_u":		"venusfinger",
                "skill_type_d":		"xifengying",
				"d_adjust":			15,
                "unarmed":		"venusfinger",
                "sword":		"tempestsword",
                "force":		"gaunforce",
                "parry":		"tempestsword",
                "dodge":		"xifengying",
				"dagger":		"dug",
		"perform_weapon_attack":"berserker/sword/tempestsword/knockdown",
		"perform_weapon_attack2":"berserker/sword/tempestsword/obliterate",
		"perform_weapon_attack3":"berserker/dagger/dug/deathtouch",
		"perform_unarmed_attack":	"berserker/unarmed/venusfinger/panguaxe",     
        ]), 
//	医生 
	([      
		"group":		"fighter_w",
		"npc":                	"healer",
                "name":			"春风",
                "class":	      	"bonze",
                "gender":		"男性",
                "skill_type_w":	      	"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"fengyu-piaoxiang",
                "d_adjust":		100,
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"fengyu-piaoxiang",
		"magic":		"essencemagic",
		"iron-cloth":		"xisui",
		"perform_weapon_attack":"bonze/staff/cloudstaff/npc_mind_sense",
		"perform_unarmed_attack":"bonze/unarmed/dabei-strike/npc_mind_sense",
		"perform_busy_d":	"bat/dodge/fengyu-piaoxiang/zonghengsihai",
		"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
      ]), 
//	魔教  	
  	([      
		"group":		"fighter_w",
		"npc":                	"sheolmagic",
		"name":			"夜叉",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"bloodystrike",
		"others2":		"liangyi-force",
		"others3":		"demon-steps",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/npc_summon1",
		"perform_unarmed_attack2":"demon/unarmed/demon-strike/npc_summon2",
		"perform_unarmed_attack3":"demon/unarmed/demon-strike/npc_summon3",
		"perform_unarmed_attack4":"demon/unarmed/demon-strike/npc_summon4",
		"perform_unarmed_attack5":"demon/unarmed/demon-strike/npc_summon5",
		"perform_busy_u1":"demon/unarmed/demon-strike/rufengsibi",
		"perform_busy_u2":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_busy_u3":"lama/unarmed/bloodystrike/fofawubian",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"feixiansword",
		"name":			"摩呼罗迦",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"sword/feixiansword",
		"w_adjust":		10,
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"sword":		"feixiansword",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"feixiansword",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"music",
		"others2":		"demon-steps",
		"others3":		"fall-steps",
		"perform_unarmed_attack":"demon/unarmed/spicyclaw/extrahit4",
		"perform_weapon_attack":"demon/sword/feixiansword/tianwaifeixian",
		"perform_busy_u":"demon/unarmed/demon-strike/npc_by_shimian",
//		"perform_busy_u":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_busy_u1":"demon/dodge/fall-steps/luoyeqiufeng",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"demonblade",
		"name":			"迦楼罗",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"blade/demon-blade",
		"skill_type_u":		"demon-strike",
		"skill_type_d":		"moon-blade",
		"blade":		"demon-blade",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-blade",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"others2":		"fall-steps",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/guishenpomie",
		"perform_weapon_attack":"demon/blade/demon-blade/npc_tiandirenmo",
		"perform_busy_d":"demon/dodge/demon-steps/lianhuanbabu",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":         	"illusionstick",
		"name":			"紧那罗",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"staff/illusionstick",
		"w_adjust":		100,
		"skill_type_u":		"kongshoudao",
		"u_adjust":		70,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"staff":		"illusionstick",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"illusionstick",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fall-steps",
		"others2":		"fengyu-piaoxiang",
		"perform_unarmed_attack":"demon/unarmed/kongshoudao/yaozhan",
		"perform_weapon_attack":"demon/staff/illusionstick/menghuantianluo",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"divineforce",
		"name":			"乾达婆",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/manaflare",
		"perform_unarmed_attack3":"demon/force/divineforce/baocanshouque",
		"perform_unarmed_attack4":"demon/force/divineforce/disorder",
		"perform_busy_d":"no_dodge_busy",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"kaleidostrike",
		"name":			"阿修罗",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_u":		"kaleidostrike",
		"u_adjust":		-15,
		// 使用时需附加apply/attack。 kld-strike coeff不高，可是高级别的影响巨大，此限。
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"kaleidostrike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fall-steps",
		"others2":		"fengyu-piaoxiang",
		"perform_unarmed_attack":"demon/unarmed/kaleidostrike/xukongyeyue",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"dragonwhip",
		"name":			"龙",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"whip/dragonwhip",
		"w_adjust":		-5,
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"whip":		"dragonwhip",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"thunderwhip",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"others2":		"fall-steps",
		"others3":		"thunderwhip",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_weapon_attack":"demon/whip/dragonwhip/thousandfeather",
		"perform_weapon_attack2":"demon/whip/dragonwhip/firestorm",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_w":"demon/whip/dragonwhip/thousandfeather",
        ]),
  	([      
		"group":		"fighter_w",
		"npc":                	"daimonsword",
		"name":			"天",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"sword/daimonsword",
		"w_adjust":		10,
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"sword":		"daimonsword",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"13-sword",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"others2":		"13-sword",
//		"others1":		"fall-steps",
//		"others3":		"fengyu-piaoxiang",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/wudumiaodi",
		"perform_weapon_attack":"demon/sword/daimonsword/libie",
		"perform_weapon_attack2":"demon/sword/daimonsword/chousi",
		"perform_weapon_attack3":"demon/sword/daimonsword/duanchang",
		"perform_busy_d":"demon/dodge/demon-steps/lianhuanbabu",
//		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
//		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",

        ]),
 	([      
		"group":		"fighter_w",
		"npc":                	"mixed_demon",
		"name":			"天龙八部",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_w":		"blade/demon-blade",
		"w_adjust":		20,
		"skill_type_u":		"kaleidostrike",
		"u_adjust":		10,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-30,
		"whip":			"dragonwhip",
		"blade":		"demon-blade",
		"sword":		"daimonsword",
		"unarmed":		"kaleidostrike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"perform_unarmed_attack2":"demon/force/divineforce/wudumiaodi",
		"perform_unarmed_attack4":"demon/force/divineforce/manaburst",
		"perform_unarmed_attack5":"demon/force/divineforce/baocanshouque",
		"perform_weapon_attack":"demon/force/divineforce/disorder",
		"perform_weapon_attack3":"demon/whip/dragonwhip/thousandfeather",
		"perform_weapon_attack4":"demon/whip/dragonwhip/firestorm",
		"perform_unarmed_attack_g":"demon/blade/demon-blade/npc_tiandirenmo",
		"perform_busy_u1":"demon/force/divineforce/npc_summon4",
		"perform_busy_u2":"demon/force/divineforce/npc_summon5",
		"perform_busy_u3":"demon/sword/daimonsword/libie",
		"perform_busy_d_g":"demon/sword/daimonsword/chousi",
		"perform_busy_u_g":"demon/sword/daimonsword/duanchang",
		"perform_busy_d":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_busy_w":"demon/whip/dragonwhip/thousandfeather",
        ]),

	// 魔教另种方案，性别对应。

  	([      
		"group":		"fighter_w",
		"npc":                	"daimonsword2",
		"name":			"天",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_w":		"blade/heavendance",
		"w_adjust":		-10,
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"blade":		"heavendance",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"zensword",
		"others2":		"zen",
		"others3":		"xiaodao",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/wudumiaodi",
		"perform_weapon_attack":"demon/blade/heavendance/yuexierenjin",
		"perform_busy_d":"demon/dodge/demon-steps/lianhuanbabu",
        ]),

 	([      
		"group":		"fighter_w",
		"npc":                	"dragonwhip2",
		"name":			"龙",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_u":		"luoriquan",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"luoriquan",
		"force":		"divineforce",
		"parry":		"luoriquan",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fengyu-piaoxiang",
		"others1":		"fall-steps",
		"perform_unarmed_attack":"demon/unarmed/luoriquan/changrijiangjin",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",
        ]),

  	([      
		"group":		"fighter_w",
		"npc":                	"kaleidostrike2",
		"name":			"阿修罗",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_u":		"kaleidostrike",
		"u_adjust":		-15,
		// 使用时需附加apply/attack。 kld-strike coeff不高，可是高级别的影响巨大，此限。
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"kaleidostrike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fall-steps",
		"others2":		"fengyu-piaoxiang",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",
        ]),

  	([      
		"group":		"fighter_w",
		"npc":                	"divineforce2",
		"name":			"乾达婆",
		"class":	      	"demon",
		"gender":		"男性",
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"demon-steps",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/lesserdeathgrip",
		"perform_unarmed_attack3":"demon/force/divineforce/baocanshouque",
		"perform_unarmed_attack4":"demon/force/divineforce/terror",
		"perform_busy_d":"no_dodge_busy",
        ]),

  	([      
		"group":		"fighter_w",
		"npc":                	"demonblade2",
		"name":			"迦楼罗",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_u":		"spicyclaw",
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"spicyclaw",
		"force":		"divineforce",
		"parry":		"spicyclaw",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"music",
		"others2":		"demon-steps",
		"others3":		"fall-steps",
		"perform_unarmed_attack":"demon/unarmed/spicyclaw/extrahit1",
		"perform_unarmed_attack2":"demon/unarmed/spicyclaw/extrahit2",
		"perform_unarmed_attack3":"demon/unarmed/spicyclaw/extrahit3",
		"perform_unarmed_attack4":"demon/unarmed/spicyclaw/extrahit4",
		"perform_unarmed_attack5":"demon/unarmed/spicyclaw/extrahit5",
		"perform_busy_u":"demon/unarmed/demon-strike/npc_by_shimian",
//		"perform_busy_u":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_busy_u1":"demon/dodge/fall-steps/luoyeqiufeng",
        ]),

	([      
		"group":		"fighter_w",
		"npc":                	"feixiansword2",
		"name":			"摩呼罗迦",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_w":		"sword/demosword",
		"w_adjust":		10,
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"sword":		"daimonsword",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fall-steps",
		"others2":		"zen",
		"others3":		"xiaodao",
		"perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
		"perform_unarmed_attack2":"demon/force/divineforce/guishenpomie",
		"perform_weapon_attack":"demon/sword/zensword/menghuankonghua",
		"perform_weapon_attack2":"demon/sword/demosword/zhutianjianzhen",
		"perform_busy_d":"legend/dodge/fall-steps/luoyeqiufeng",
        ]),

   	([      
		"group":		"fighter_w",
		"npc":         	"illusionstick2",
		"name":			"紧那罗",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_w":		"spells/devil-spells",
		"w_adjust":		40,
		"skill_type_u":		"kongshoudao",
		"u_adjust":		70,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"spells":		"devil-spells",
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"illusionstick",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"fall-steps",
		"others2":		"fengyu-piaoxiang",
		"others3":		"eagle-claw",
//		"perform_weapon_attack":"demon/staff/illusionstick/menghuantianluo",
		"perform_busy_d":"demon/dodge/fall-steps/luoyeqiufeng",
		"perform_busy_u1":"bat/dodge/fengyu-piaoxiang/zonghengsihai",
		"perform_busy_u2":"fugui/unarmed/eagle-claw/shizhiqinlong",
        ]),

  	([      
		"group":		"fighter_w",
		"npc":                	"sheolmagic2",
		"name":			"夜叉",
		"class":	      	"demon",
		"gender":		"女性",
		"skill_type_u":		"demon-strike",
		"u_adjust":		15,
		"skill_type_d":		"moon-blade",
		"d_adjust":		-50,
		"unarmed":		"demon-strike",
		"force":		"divineforce",
		"parry":		"demon-strike",
		"dodge":		"moon-blade",
		"magic":		"sheolmagic",
		"others1":		"bloodystrike",
		"others2":		"liangyi-force",
		"others3":		"demon-steps",
		"perform_busy_u1":"demon/unarmed/demon-strike/rufengsibi",
		"perform_busy_u2":"demon/dodge/demon-steps/lianhuanbabu",
		"perform_busy_u3":"lama/unarmed/bloodystrike/fofawubian",
        ]),

});


mapping query_npc(string group_name, string npc_name, int special){
	
	int total/*,i*/,x,n,m;
//	string npc;
	
	total=sizeof(npctype);
	n=1;
	m=total;
	
	if (npc_name=="random") {
		if (group_name=="random") { 
			while (m) {
				x=random(total-17);	// 在 random/random中暂时不出现的ＮＰＣ
				if (npctype[x]["npc"]!="taiji" && npctype[x]["npc"]!="taiji-sword"
					&& npctype[x]["npc"]!= "mapo") m=0;
					else
						CHANNEL_D->do_sys_channel("sys",sprintf("%s can busy to death, discarded", npctype[x]["npc"]));
			}
		}			
		else while(n) {
			x=random(total);
			if (npctype[x]["group"]==group_name) n=0;
			}
	} else {
		while (m--) {
			if (npctype[m]["npc"]==npc_name) {
				x=m; break;		
			}
		} 
	}	
	return npctype[x];
}



int total_npc(){
	return sizeof(npctype);
}

mapping *npclist(){
	return npctype;
}