/*  OK, we need three ranges of SMART_NPCs,

(1) NPC_BAS, 
	0-5M,  menpai skill only, Can have defense-parry, 
(2) NPC_MID, 
	5-10M  + all free-master skills and couple skill. 
	random_allowed in (5-15M);
(3) NPC_ADV, 
	10-15M + advanced basic, + haste/double, + adv-perk. 

	初级NPC
	此NPCLIST和相应的do_choose_attack_1用以处理一般的NPC引用，
	强弱由perform frequency 决定。
	如果你不明白，那么３０是一个安全的选择。
	
	Example:
	    set("chat_chance_combat", 100);
    	set("chat_msg_combat", ({
	    	 (: auto_smart_fight(20) :),
        }) );
		
	你也可以只引用auto_setup设置而不引用Smart_fight.
	
	0-5M 此表共计78个NPC，1个random NPC。
	
	------- by Silencer@fy2005 workgroup 8/2005
	
*/

inherit SKILL;

mapping *npctype = ({
	//	随机的小喽罗。打法ok但并非优化。	
// This will generate a random skill NPC. Do not specify his weapon since he uses varies skills.
// He has some dodge/unarmed busy and a weapon attaack, difficulty moderate I would say.
// You can use it as 小喽罗.
	([      
		"group":		"fighter_w",
		"npc":                	"smallguy",
                "name":			"小喽罗",
                "class":	      	"lama",
                "gender":		"男性",
                "force":		"manjianghong",
		"others1":		"bloodystrike",
		"others2":		"strategy",
		"others3":		"leadership",
		"perform_weapon_attack": "random",
		"perform_unarmed_attack":"random",
		"perform_busy_d":	 "random",
		"perform_busy_u":	 "random",
        ]),
//	铁雪family/master_id		40
	([      
				"group":				"fighter_w",
				"npc":          		"diesword",
                "name":					"蝶恋花",
                "class":	    		"legend",
                "gender":				"女性",
                "skill_type_w":	    	"sword/diesword",
                "skill_type_u":			"meihua-shou",
                "skill_type_d":			"fall-steps",
                "unarmed":				"meihua-shou",
                "sword":				"diesword",
                "force":				"qidaoforce",
                "parry":				"diesword",
                "dodge":				"fall-steps",
                "others1":				"dormancy",
                "others2":				"six-sense",
                "perform_weapon_attack":"legend/sword/diesword/caidiekuangwu",
				"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
				"perform_busy_u":		"legend/unarmed/meihua-shou/meihai",
				"set_master":			"master xuerui",        
        ]),   
       	([      
		"group":		"fighter_w",
		"npc":                	"shortsong-blade",
                "name":				"短歌长梦",
                "class":	      	"legend",
                "gender":			"男性",
                "skill_type_w":	   	"blade/shortsong-blade",
                "skill_type_u":		"meihua-shou",
                "skill_type_d":		"fall-steps",
                "unarmed":		"meihua-shou",
                "blade":		"shortsong-blade",
                "force":		"qidaoforce",
                "parry":		"shortsong-blade",
                "dodge":		"fall-steps",
                "others1":		"dormancy",
                "others2":		"six-sense",
                "perform_weapon_attack":"legend/blade/shortsong-blade/duangechangmeng",
				"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
				"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",
        ]),
//	丐帮        			90
  	([      
		"group":		"fighter_w",
		"npc":                	"dragonstrike",
                "name":			"上官十",
                "class":	    "beggar",
                "gender":		"男性",
                "skill_type_u":	"dragonstrike",
                "skill_type_d":	"doggiesteps",
                "unarmed":		"dragonstrike",
                "force":		"huntunforce",
                "dodge":		"doggiesteps",
                "others1":		"begging",
                "perform_unarmed_attack":"beggar/unarmed/dragonstrike/xianglongwuhui",
                "perform_unarmed_attack2":"beggar/unarmed/dragonstrike/shichengliulong",
                "perform_unarmed_attack3":"beggar/unarmed/dragonstrike/zhenjingbaili",	
        ]),  
  	([      
		"group":		"fighter_w",
		"npc":                	"dragonstrike-jg",
                "name":			"金伯生疑",
                "class":	    "beggar",
                "gender":		"男性",
                "skill_type_u":	"dragonstrike",
                "skill_type_d":	"doggiesteps",
                "unarmed":		"dragonstrike",
                "force":		"huntunforce",
                "dodge":		"doggiesteps",
                "iron-cloth":	"jin-gang",
                "force":		"huntunforce",
                "others1":		"begging",
                "perform_unarmed_attack":"beggar/unarmed/dragonstrike/xianglongwuhui",
        ]),  
	([      
		"group":		"fighter_w",
		"npc":                	"dagou-stick",
                "name":			"上官十",
                "class":	      	"beggar",
                "gender":		"男性",
                "skill_type_w":	      	"staff/dagou-stick",
                "skill_type_u":		"dragonstrike",
                "skill_type_d":		"doggiesteps",
                "unarmed":		"dragonstrike",
                "staff":		"dagou-stick",
                "force":		"huntunforce",
                "parry":		"dagou-stick",
                "dodge":		"doggiesteps",
                "others1":		"begging",
                "perform_weapon_attack":"beggar/staff/dagou-stick/tianxiawugou",
				"perform_weapon_attack2":"beggar/staff/dagou-stick/chuozijue",
				"perform_unarmed_attack":"beggar/unarmed/dragonstrike/xianglongwuhui",
				"perform_busy_w":	"beggar/staff/dagou-stick/banzijue", 
        ]),   
//	快活林
  	([      
		"group":		"magician",
		"npc":                	"herb",
                "name":			"药理",
                "class":	      	"knight",
                "gender":		"男性",
                "skill_type_w":	   	"axe/xuanyuan-axe",
                "skill_type_u":		"hanshan-strike",
                "skill_type_d":		"windy-steps",
                "herb":			"dream-herb",
                "unarmed":		"hanshan-strike",
                "axe":			"xuanyuan-axe",
                "force":		"longlife-force",
                "parry":		"xuanyuan-axe",
                "dodge":		"windy-steps",
				"perform_unarmed_attack":"knight/herb/dream-herb/canyunbi",
				"perform_unarmed_attack2": "knight/unarmed/hanshan-strike/zhangjian",
				"perform_weapon_attack": "knight/axe/xuanyuan-axe/guifushengong",
				"perform_busy_d":       "knight/herb/dream-herb/kaixiehua",
        ]), 
         ([      
		"group":		"fighter_w",
		"npc":                	"xuanyuan-axe",
                "name":			"轩辕斧",
                "class":	      	"knight",
                "gender":		"男性",
                "skill_type_w":	      	"axe/xuanyuan-axe",
                "skill_type_u":		"hanshan-strike",
                "skill_type_d":		"windy-steps",
                "herb":			"dream-herb",
                "unarmed":		"hanshan-strike",
                "axe":			"xuanyuan-axe",
                "force":		"longlife-force",
                "parry":		"xuanyuan-axe",
                "dodge":		"windy-steps",
				"perform_weapon_attack":"knight/axe/xuanyuan-axe/guifushengong",
				"perform_weapon_attack2":"knight/axe/xuanyuan-axe/jiuqipoxiao",
				"perform_unarmed_attack":"knight/unarmed/hanshan-strike/zhangjian",
				"perform_unarmed_attack2":"knight/herb/dream-herb/beisusan",
				"perform_busy_d":       "knight/herb/dream-herb/kaixiehua",
        ]), 
         ([      
		"group":		"fighter_w",
		"npc":                	"zhangjian",
                "name":			"轩辕斧",
                "class":	      	"knight",
                "gender":		"男性",
				"skill_type_u":		"hanshan-strike",
                "skill_type_d":		"windy-steps",
                "herb":			"dream-herb",
                "unarmed":		"hanshan-strike",
                "force":		"longlife-force",
                "dodge":		"windy-steps",
				"perform_unarmed_attack":"knight/unarmed/hanshan-strike/zhangjian",
				"perform_busy_d":       "knight/herb/dream-herb/kaixiehua",
        ]), 
// 	金钱
        ([    
        	"group":		"fighter_w",
			"npc":             	"sharen-sword",
                "name":			"小飞",
                "class":	   	"assassin",
                "gender":		"男性",
                "skill_type_w":	   	"sword/sharen-sword",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "unarmed":		"flame-strike",
                "sword":		"sharen-sword",
                "force":		"jingxing",
                "parry":		"lefthand-sword",
                "dodge":		"jinhong-steps",
                "others1":		"lefthand-sword",
				"perform_weapon_attack":"assassin/sword/sharen-sword/sharenruma",
				"perform_unarmed_attack":"assassin/dodge/jinhong-steps/canglongzhaxian",
        ]),  
        ([    
        	"group":		"fighter_w",
			"npc":                	"lefthand-sword",
                "name":			"小飞",
                "class":	   	"assassin",
                "gender":		"男性",
                "skill_type_w":   	"sword/lefthand-sword",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "unarmed":		"flame-strike",
                "sword":		"lefthand-sword",
                "force":		"jingxing",
                "parry":		"lefthand-sword",
                "dodge":		"jinhong-steps",
                "perform_weapon_attack": "assassin/sword/lefthand-sword/duxin",
				"perform_unarmed_attack":"assassin/dodge/jinhong-steps/canglongzhaxian",
        ]),  
        ([    
        	"group":		"fighter_w",
			"npc":         	"longfenghuan",
                "name":			"云",
                "class":	   	"assassin",
                "gender":		"男性",
                "skill_type_w":    	"hammer/longfenghuan",
                "skill_type_u":		"flame-strike",
                "skill_type_d":		"jinhong-steps",
                "unarmed":		"flame-strike",
                "hammer":		"longfenghuan",
                "force":		"jingxing",
                "parry":		"longfenghuan",
                "dodge":		"jinhong-steps",
                "perform_weapon_attack":"assassin/hammer/longfenghuan/longfengshuangfei",
				"perform_unarmed_attack":"assassin/dodge/jinhong-steps/canglongzhaxian",
        ]),  
//	神水
  	([      
		"group":		"fighter_w",
		"npc":                	"nine-moon-claw",
                "name":			"下着雨",
                "class":	      	"shenshui",
                "gender":		"女性",
                "skill_type_u":		"nine-moon-claw",
                "skill_type_d":		"nine-moon-steps",
                "unarmed":		"nine-moon-claw",
                "force":		"nine-moon-force",
                "dodge":		"nine-moon-steps",
				"others1":		"nine-moon-spirit",
				"others2":		"buddhism",
				"perform_unarmed_attack":"shenshui/unarmed/nine-moon-claw/polu",
				"set_temp1":		"nine-moon-force_poison",           
        ]),  
        ([      
		"group":		"fighter_w",
		"npc":                	"nine-moon-sword",
                "name":			"明月",
                "class":	      	"shenshui",
                "gender":		"女性",
                "skill_type_w":	      	"sword/nine-moon-sword",
                "skill_type_u":		"nine-moon-claw",
                "skill_type_d":		"nine-moon-steps",
                "unarmed":		"nine-moon-claw",
                "sword":		"nine-moon-sword",
                "force":		"nine-moon-force",
                 "parry":		"qingpingsword",
                "dodge":		"nine-moon-steps",
				"others1":		"nine-moon-spirit",
				"perform_weapon_attack":"shenshui/sword/nine-moon-sword/shuanglengcanxia",
				"perform_busy_w":	"shenshui/sword/nine-moon-sword/yanduhantan",
				"set_temp1":		"nine-moon-force_poison",           
        ]), 
	([      
		"group":		"fighter_w",
		"npc":                	"nine-moon-sword2",
                "name":			"天正下着雨",
                "class":	      	"shenshui",
                "gender":		"女性",
                "skill_type_w":	      	"sword/nine-moon-sword",
                "skill_type_u":		"nine-moon-claw",
                "skill_type_d":		"nine-moon-steps",
                "unarmed":		"nine-moon-claw",
                "sword":		"nine-moon-sword",
                "force":		"nine-moon-force",
                "parry":		"qingpingsword",
                "dodge":		"nine-moon-steps",
				"others1":		"nine-moon-spirit",
				"perform_weapon_attack":"shenshui/sword/nine-moon-sword/shuanglengcanxia",
				"perform_unarmed_attack":"shenshui/unarmed/nine-moon-claw/polu",
				"perform_busy_d":	"shenshui/dodge/nine-moon-steps/lianhuanbu",
				"perform_busy_w":	"shenshui/sword/nine-moon-sword/yanduhantan",
				"set_temp1":		"nine-moon-force_poison",           
        ]), 
//	帝王谷
	([      
		"group":		"fighter_w",
		"npc":                	"thunderwhip",
                "name":			"小狂刀",
                "class":	      	"yinshi",
                "gender":		"男性",
                "skill_type_w":	      	"whip/thunderwhip",
                "skill_type_u":		"pofeng-strike",
                "skill_type_d":		"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "hammer":		"pangu-hammer",
                "force":		"iceheart",
                "parry":		"thunderwhip",
                "dodge":		"zuixian-steps",
                "whip":			"thunderwhip",
                "cursism":		"celecurse",
                "others2":		"qiankunwuxing",
				"perform_weapon_attack": "yinshi/whip/thunderwhip/yunlongjiuxian",
				"perform_unarmed_attack":"yinshi/unarmed/pofeng-strike/luanpofeng",
        ]),
        ([      
		"group":		"fighter_w",
		"npc":                	"thunderwhip2",
                "name":			"小狂刀",
                "class":	      	"yinshi",
                "gender":		"男性",
                "skill_type_w":	      	"whip/thunderwhip",
                "skill_type_u":		"pofeng-strike",
                "skill_type_d":		"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "hammer":		"pangu-hammer",
                "force":		"iceheart",
                "parry":		"thunderwhip",
                "dodge":		"zuixian-steps",
                "whip":			"thunderwhip",
                "cursism":		"celecurse",
				"perform_weapon_attack":"yinshi/whip/thunderwhip/tianleiyiji",
				"perform_unarmed_attack":"yinshi/unarmed/pofeng-strike/luanpofeng",
        ]),
        ([      
		"group":		"fighter_w",
		"npc":                	"pangu-hammer",
                "name":			"小狂刀",
                "class":	    "yinshi",
                "gender":		"男性",
                "skill_type_w":	      	"hammer/pangu-hammer",
                "skill_type_u":		"pofeng-strike",
                "skill_type_d":		"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "hammer":		"pangu-hammer",
                "force":		"iceheart",
                "parry":		"pangu-hammer",
                "dodge":		"zuixian-steps",
                "cursism":		"celecurse",
                "others1":		"dabei-strike",
				"perform_weapon_attack":"yinshi/hammer/pangu-hammer/kaitianpidi",
				"perform_unarmed_attack":"yinshi/unarmed/pofeng-strike/luanpofeng",
//				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
				"set_1":		"marks/hammerwhip",
        ]),
        ([      
		"group":		"magician",
		"npc":                	"celecurse1",
                "name":			"小狂刀",
                "class":	     "yinshi",
                "gender":		"男性",
                "skill_type_w": "whip/thunderwhip",
                "skill_type_u":	"pofeng-strike",
                "skill_type_d":	"zuixian-steps",
                "unarmed":		"pofeng-strike",
                "hammer":		"pangu-hammer",
                "force":		"iceheart",
                "parry":		"thunderwhip",
                "dodge":		"zuixian-steps",
                "whip":			"thunderwhip",
                "cursism":		"celecurse",
				"perform_unarmed_attack":"yinshi/cursism/celecurse/bloodcurse",
        ]),
//	华山	Spring-water perform isn't required due to higher level for NPCs
	([      
		"group":		"fighter_w",
		"npc":                	"tanzhi-shentong",
                "name":			"红月光",
                "class":	    "huashan",
                "gender":		"女性",
                "skill_type_w":	 "throwing/tanzhi-shentong",
                "skill_type_u":	"zhaixin-claw",
                "skill_type_d":	"cloud-dance",
                "unarmed":		"zhaixin-claw",
                "force":		"hanmei-force",
                "dodge":		"cloud-dance",
                "parry":		"tanzhi-shentong",
                "throwing":		"tanzhi-shentong",
				"iron-cloth":		"spring-water",
				"perform_weapon_attack":"huashan/throwing/tanzhi-shentong/mantianhuayu",
				"perform_busy_d":       "huashan/dodge/cloud-dance/yexuechuji",
        ]),
        ([      
		"group":		"fighter_w",
		"npc":                	"tanzhi-shentong2",
                "name":			"红月光",
                "class":	      	"huashan",
                "gender":		"女性",
                "skill_type_w":	    "throwing/tanzhi-shentong",
                "skill_type_u":		"zhaixin-claw",
                "skill_type_d":		"cloud-dance",
                "unarmed":		"zhaixin-claw",
                "force":		"hanmei-force",
                "dodge":		"cloud-dance",
                "parry":		"tanzhi-shentong",
                "throwing":		"tanzhi-shentong",
				"iron-cloth":		"spring-water",
				"perform_weapon_attack":"huashan/throwing/tanzhi-shentong/mantianhuayu",
				"perform_busy_u":       "huashan/throwing/tanzhi-shentong/tanzhijinghun",
        ]),
        ([      
		"group":		"fighter_w",
		"npc":                	"qingfeng-sword",
                "name":			"蓝月光",
                "class":	     "huashan",
                "gender":		"女性",
                "skill_type_w":	 "sword/qingfeng-sword",
                "skill_type_u":	"zhaixin-claw",
                "skill_type_d":	"cloud-dance",
                "unarmed":		"zhaixin-claw",
                "sword":		"qingfeng-sword",
                "force":		"hanmei-force",
                "parry":		"qingfeng-sword",
                "dodge":		"cloud-dance",
				"iron-cloth":		"spring-water",
				"perform_unarmed_attack":"huashan/force/hanmei-force/chill",
				"perform_busy_d":       "huashan/dodge/cloud-dance/yexuechuji",
        ]), 
//	武当
        ([      
		"group":		"fighter_w",
		"npc":                	"taiji",
                "name":			"阿龙",
                "class":	      	"wudang",
                "gender":		"男性",
                "skill_type_u":		"taiji",
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "force":		"taijiforce",
                "dodge":		"five-steps",
				"perform_busy_u":	"wudang/unarmed/taiji/nianzijue",
				"perform_unarmed_attack":"wudang/unarmed/taiji/nianzijue",
        ]),  
		([      
		"group":		"fighter_w",
		"npc":                	"taiji-sword",
                "name":			"蝴蝶",
                "class":	      	"wudang",
                "gender":		"女性",
                "skill_type_w":	      	"sword/taiji-sword",
                "skill_type_u":		"taiji",
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "sword":		"taiji-sword",
                "force":		"taijiforce",
                "parry":		"taiji-sword",
                "dodge":		"five-steps",
                "perform_busy_w":	"wudang/sword/taiji-sword/chanzijue",
        ]), 
        ([      
		"group":		"fighter_w",
		"npc":                	"three-sword",
                "name":			"蝴蝶",
                "class":	      	"wudang",
                "gender":		"女性",
                "skill_type_w":	      	"sword/three-sword",
                "skill_type_u":		"taiji",
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "sword":		"three-sword",
                "force":		"taijiforce",
                "parry":		"three-sword",
                "dodge":		"five-steps",
                "others1":		"changelaw",
                "perform_busy_w":	"npc/sword/three-sword/nianzijue",
        ]), 
        ([      
		"group":		"fighter_w",
		"npc":                	"three-sword2",
                "name":			"蝴蝶",
                "class":	      	"wudang",
                "gender":		"女性",
                "skill_type_w":	      	"sword/three-sword",
                "skill_type_u":		"taiji",
                "skill_type_d":		"five-steps",
                "unarmed":		"taiji",
                "sword":		"three-sword",
                "force":		"taijiforce",
                "parry":		"three-sword",
                "dodge":		"five-steps",
                "others1":		"changelaw",
                "perform_weapon_attack":"npc/sword/three-sword/sancai",
        ]), 
//	兴国
	([      
		"group":		"fighter_w",
		"npc":                	"cloudstaff",
                "name":			"苦苦",
                "class":	    "bonze",
                "gender":		"男性",
                "skill_type_w":		"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"nodust-steps",
				"magic":		"essencemagic",
				"perform_weapon_attack":"bonze/staff/cloudstaff/longxianyuye",
				"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
        ]), 
	([      
		"group":		"magician",
		"npc":                	"mind-sense",
                "name":			"笨笨",
                "class":	      	"bonze",
                "gender":		"男性",
                "skill_type_w":	      	"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"nodust-steps",
				"magic":		"essencemagic",
				"perform_unarmed_attack":"bonze/magic/essencemagic/mind_sense",
				"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
      	]), 
//	少林
	  	([      
		"group":		"fighter_w",
		"npc":                	"fumostaff",
                "name":			"伏魔杖",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_w":	 "staff/fumostaff",
                "skill_type_u":	"dabei-strike",
                "skill_type_d":	"puti-steps",
                "staff":		"fumostaff",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"fumostaff",
                "dodge":		"puti-steps",
                "perform_busy_w":"shaolin/staff/fumostaff/hequhecong",
				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),   
  	([      
		"group":		"fighter_w",
		"npc":                	"lianxin-blade",
                "name":			"莲心刀",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	      	"blade/lianxin-blade",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"puti-steps",
                "blade":		"lianxin-blade",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"lianxin-blade",
                "dodge":		"puti-steps",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),   
        ([      
		"group":		"fighter_w",
		"npc":                	"tianlongwhip",
                "name":			"天龙鞭",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	      	"whip/tianlongwhip",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"puti-steps",
                "whip":			"tianlongwhip",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"tianlongwhip",
                "dodge":		"puti-steps",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),  
        ([      
		"group":		"fighter_w",
		"npc":                	"xingyi-stick",
                "name":			"兴衣棍",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	      	"staff/xingyi-stick",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"puti-steps",
                "staff":		"xingyi-stick",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"xingyi-stick",
                "dodge":		"puti-steps",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),  
  	([      
		"group":		"fighter_w",
		"npc":                	"wuche-axe",
                "name":			"悟彻斧",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	  	"axe/wuche-axe",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"puti-steps",
                "axe":			"wuche-axe",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"wuche-axe",
                "dodge":		"puti-steps",
				"perform_weapon_attack":"shaolin/axe/wuche-axe/sanbanfu",
				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),    
        ([      
		"group":		"fighter_w",
		"npc":                	"liuxing-hammer",
                "name":			"流星锤",
                "class":	      	"shaolin",
                "gender":		"男性",
                "skill_type_w":	      	"hammer/liuxing-hammer",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"puti-steps",
                "hammer":		"liuxing-hammer",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "parry":		"liuxing-hammer",
                "dodge":		"puti-steps",
				"perform_weapon_attack":"shaolin/hammer/liuxing-hammer/fanbei",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),   
  	([      
		"group":		"fighter_u",
		"npc":                	"dabei-strike",
                "name":			"小天意",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_u":	"dabei-strike",
                "skill_type_d":	"puti-steps",
                "unarmed":		"dabei-strike",
                "force":		"xiaochengforce",
                "dodge":		"puti-steps",
                "iron-cloth":	"xisui",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),   	
  	([      
		"group":		"fighter_u",
		"npc":                	"yijinjing",
                "name":			"小天意",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_u":	"yizhichan",
                "skill_type_d":	"puti-steps",
                "unarmed":		"yijinjing",
                "force":		"xiaochengforce",
                "dodge":		"puti-steps",
                "iron-cloth":	"yijinjing",
				"others1":		"dabei-strike",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),   
          	([      
		"group":		"fighter_u",
		"npc":                	"yiyangzhi",
                "name":			"小天意",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_u":	"yiyangzhi",
                "skill_type_d":	"puti-steps",
                "unarmed":		"yiyangzhi",
                "force":		"xiaochengforce",
                "dodge":		"puti-steps",
                "iron-cloth":	"xisui",
				"others1":		"dabei-strike",
				"perform_unarmed_attack":"shaolin/unarmed/yiyangzhi/qiankun",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]), 
        ([      
		"group":		"fighter_u",
		"npc":                	"yiyangzhi2",
                "name":			"小天意",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_u":	"yiyangzhi",
                "skill_type_d":	"puti-steps",
                "unarmed":		"yiyangzhi",
                "force":		"xiaochengforce",
                "dodge":		"puti-steps",
                "iron-cloth":	"xisui",
				"others1":		"dabei-strike",
				"perform_unarmed_attack":"shaolin/unarmed/yiyangzhi/qiankun",
        ]),  
       ([
        "group":		"fighter_u",
		"npc":                	"yizhichan",
                "name":			"小天意",
                "class":	     "shaolin",
                "gender":		"男性",
                "skill_type_u":	"yizhichan",
                "skill_type_d":	"puti-steps",
                "unarmed":		"yizhichan",
                "force":		"xiaochengforce",
                "dodge":		"puti-steps",
                "iron-cloth":	"yijinjing",
				"others1":		"dabei-strike",
				"perform_busy_u":"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),
        ([      
		"group":		"fighter_u",
		"npc":                	"huidashi",
                "name":			"慧大师",
                "class":	    "shaolin",
                "gender":		"男性",
                "skill_type_u":	"yijinjing",
                "skill_type_d":	"puti-steps",
                "unarmed":		"yue-strike",
                "force":		"yijinjing",
                "dodge":		"puti-steps",
                "iron-cloth":	"yijinjing",
				"others1":		"dabei-strike",
        ]), 
//	神剑  
	([      
		"group":		"fighter_w",
		"npc":                	"softsword",
                "name":			"天意梦断",
                "class":	    "swordsman",
                "gender":		"男性",
                "skill_type_w":	   	"sword/softsword",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"shadowsteps",
                "unarmed":		"dabei-strike",
                "sword":		"softsword",
                "force":		"cloudforce",
                "parry":		"softsword",
                "dodge":		"shadowsteps",
				"perform_weapon_attack":"swordsman/sword/softsword/npc_sword_muyu",
				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]), 
        ([      
		"group":		"fighter_u",
		"npc":                	"shadowsteps",
                "name":			"天意梦断",
                "class":	      	"swordsman",
                "gender":		"男性",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"shadowsteps",
                "unarmed":		"dabei-strike",
                "force":		"cloudforce",
                "dodge":		"shadowsteps",
				"perform_unarmed_attack":"swordsman/dodge/shadowsteps/lianhuanjiao",
				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]), 
	([      
		"group":		"fighter_u",
		"npc":                	"shadowsteps+dragon",
                "name":			"谢二",
                "class":	      	"swordsman",
                "gender":		"男性",
                "skill_type_u":		"dragonstrike",
                "skill_type_d":		"shadowsteps",
                "unarmed":		"dragonstrike",
                "force":		"cloudforce",
                "dodge":		"shadowsteps",
                "others1":		"dabei-strike",
				"perform_unarmed_attack":"swordsman/dodge/shadowsteps/lianhuanjiao",
				"perform_busy_u":	"shaolin/unarmed/dabei-strike/qianshouqianbian",
        ]),
	([      
		"group":		"fighter_u",
		"npc":                	"shadowsteps+lingxi",
                "name":			"谢三",
                "class":	      	"swordsman",
                "gender":		"男性",
                "skill_type_u":		"lingxi-zhi",
                "skill_type_d":		"shadowsteps",
                 "unarmed":		"lingxi-zhi",
                "force":		"cloudforce",
                "dodge":		"shadowsteps",
                "perform_unarmed_attack":"swordsman/dodge/shadowsteps/lianhuanjiao",
        ]),
//	万梅
        ([      
		"group":		"fighter_w",
		"npc":                	"doomsword",
                "name":			"东门飞雪",
                "class":	      	"fighter",
                "gender":		"女性",
                "skill_type_w":	      	"sword/doomsword",
                "skill_type_u":		"doomstrike",
                "skill_type_d":		"doomsteps",
                "unarmed":		"doomstrike",
                "sword":		"doomsword",
                "force":		"doomforce",
                "parry":		"doomsword",
                "dodge":		"doomsteps",
				"others1":		"meihua-shou",
				"perform_weapon_attack":"fighter/sword/doomsword/hunranyijian",
				"perform_unarmed_attack":"fighter/unarmed/doomstrike/hantian",
				"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",
        ]), 
        ([      
		"group":		"fighter_u",
		"npc":                	"doomstrike",
                "name":			"东门飞雪",
                "class":	      	"fighter",
                "gender":		"女性",
                "skill_type_u":		"doomstrike",
                "skill_type_d":		"doomsteps",
                "unarmed":		"doomstrike",
                "force":		"doomforce",
                "parry":		"doomsword",
                "dodge":		"doomsteps",
				"others1":		"meihua-shou",
				"perform_unarmed_attack":"fighter/unarmed/doomstrike/hantian",
				"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",
        ]), 
//	富贵
	 	([      
		"group":		"fighter_w",
		"npc":                	"xuezhan-spear",
                "name":			"阿铭",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_w":	   	"spear/xuezhan-spear",
                "skill_type_u":		"eagle-claw",
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
				"iron-cloth":	"henglian",
				"perform_weapon_attack":"fugui/spear/xuezhan-spear/yutianbigao",
        ]),    
        ([      
		"group":		"fighter_w",
		"npc":         	"xuezhan-spear2",
                "name":			"阿铭",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_w":	   	"spear/xuezhan-spear",
                "skill_type_u":		"eagle-claw",
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
				"iron-cloth":	"henglian",
				"perform_weapon_attack":"fugui/spear/xuezhan-spear/jinshiweikai",
				"perform_unarmed_attack":"fugui/unarmed/eagle-claw/cunjin",
				"perform_busy_w":  		"fugui/spear/xuezhan-spear/wulongbaiwei",
        ]),       
        ([      
		"group":		"fighter_u",
		"npc":                	"eagle-claw",
                "name":			"鹰爪王",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_u":		"eagle-claw",
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
				"iron-cloth":	"henglian",
				"perform_busy_d":       "fugui/dodge/hawk-steps/yingjichangkong",
				"perform_unarmed_attack":"fugui/unarmed/eagle-claw/cunjin",
        ]),         
        ([      // Old style
		"group":		"fighter_w",
		"npc":                	"xuezhan-spear3",
                "name":			"阿铭",
                "class":	      	"fugui",
                "gender":		"男性",
                "skill_type_w":	      	"spear/xuezhan-spear",
                "skill_type_u":		"eagle-claw",
                "skill_type_d":		"hawk-steps",
                "unarmed":		"eagle-claw",
                "spear":		"xuezhan-spear",
                "force":		"skyforce",
                "parry":		"xuezhan-spear",
                "dodge":		"hawk-steps",
				"iron-cloth":		"henglian",
				"perform_weapon_attack":"fugui/spear/xuezhan-spear/bafangfengyu",
				"perform_weapon_attack2":"fugui/spear/xuezhan-spear/jinshiweikai",
				"perform_busy_w":  		"fugui/spear/xuezhan-spear/wulongbaiwei",
        ]),   
//	蝙蝠  
        ([      
		"group":		"fighter_w",
		"npc":                	"bat-blade",
                "name":			"袁青谷",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_w":	  "blade/bat-blade",
                "skill_type_u":	  "luoriquan",
                "skill_type_d":	  "meng-steps",
                "unarmed":		"luoriquan",
                "blade":		"bat-blade",
                "parry":		"bat-blade",
                "force": 		"wuzheng-force",
                "dodge":		"meng-steps",
                "perform_weapon_attack":"bat/blade/bat-blade/shiwanshenmo",
				"perform_busy_d":       "bat/dodge/meng-steps/huanyinqianchong",
        ]), 
//	魔教
	([      
		"group":		"fighter_w",
		"npc":                	"tianmo",
                "name":			"天魔",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_u":		"demon-strike",
                "skill_type_d":		"demon-steps",
                "unarmed":		"demon-strike",
                 "dodge":		"demon-steps",
                 "force":		"demon-force",
                "perform_unarmed_attack":"demon/unarmed/demon-strike/tianmo",
				"perform_busy_d":       "demon/dodge/demon-steps/lianhuanbabu",
        ]),         
        ([      
		"group":		"fighter_w",
		"npc":                	"renmo",
                "name":			"人魔",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_u":		"demon-strike",
                "skill_type_d":		"demon-steps",
                "unarmed":		"demon-strike",
                 "dodge":		"demon-steps",
                 "force":		"demon-force",
                "perform_unarmed_attack":"demon/unarmed/demon-strike/renmo",
				"perform_busy_d":       "demon/dodge/demon-steps/lianhuanbabu",
        ]),  
        	([      
		"group":		"fighter_w",
		"npc":                	"dimo",
                "name":			"地魔",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_u":		"demon-strike",
                "skill_type_d":		"demon-steps",
                "unarmed":		"demon-strike",
                 "dodge":		"demon-steps",
                 "force":		"demon-force",
                "perform_unarmed_attack":"demon/unarmed/demon-strike/dimo",
				"perform_busy_d":       "demon/dodge/demon-steps/lianhuanbabu",
        ]),  
//	天枫
        ([      
		"group":		"fighter_w",
		"npc":                		"ittouryu",
                "name":				"恶鬼",
                "class":	      	"ninja",
                "gender":			"女性",
                "skill_type_w":	   	"blade/ittouryu",
                "skill_type_u":		"enmeiryu",
                "skill_type_d":		"ghosty-steps",
                "unarmed":		"enmeiryu",
                "blade":		"ittouryu",
                "force":		"ghosty-force",
                "parry":		"ittouryu",
                "dodge":		"ghosty-steps",
				"perform_weapon_attack":"ninja/blade/ittouryu/hyakki",
				"perform_weapon_attack2":"ninja/blade/ittouryu/gobankiri",					
				"perform_unarmed_attack":"ninja/unarmed/enmeiryu/shiden",					
				"perform_unarmed_attack2":"ninja/unarmed/enmeiryu/shimon",
        ]), 
        ([      
		"group":		"fighter_w",
		"npc":                	"ittouryu2",
                "name":			"恶鬼",
                "class":	      	"ninja",
                "gender":		"女性",
                "skill_type_w":	      	"blade/ittouryu",
                "skill_type_u":		"enmeiryu",
                "skill_type_d":		"ghosty-steps",
                "unarmed":		"enmeiryu",
                "blade":		"ittouryu",
                "force":		"ghosty-force",
                "parry":		"ittouryu",
                "dodge":		"ghosty-steps",
				"perform_weapon_attack":"ninja/blade/ittouryu/gobankiri",
				"perform_unarmed_attack":"ninja/unarmed/enmeiryu/shiden",
        ]), 
        ([      
		"group":		"fighter_w",
		"npc":                	"enmeiryu",
                "name":			"恶鬼",
                "class":	      	"ninja",
                "gender":		"女性",
                "skill_type_u":		"enmeiryu",
                "skill_type_d":		"ghosty-steps",
                "unarmed":		"enmeiryu",
                "blade":		"ittouryu",
                "force":		"ghosty-force",
                "dodge":		"ghosty-steps",
				"parry":		"bloodystrike",
				"others1":		"bloodystrike",
				"perform_unarmed_attack":"ninja/unarmed/enmeiryu/shiden",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]), 
//	官府
	([      
		"group":		"fighter_w",
		"npc":                	"yue-spear",
                "name":			"无聊",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"fall-steps",
                "unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"fall-steps",
				"others1":		"bloodystrike",
				"others2":		"strategy",
				"others3":		"leadership",
				"perform_weapon_attack":"official/spear/yue-spear/zonghengtianxia",
				"perform_unarmed_attack":"official/unarmed/changquan/yuhuan",
				"perform_busy_d":       "legend/dodge/fall-steps/luoyeqiufeng",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]), 
	([      
		"group":		"fighter_w",
		"npc":                	"yue-spear2",
                "name":			"土土",
                "class":	      	"official",
                "gender":		"女性",
                "skill_type_w":	      	"spear/yue-spear",
                "skill_type_u":		"changquan",
                "skill_type_d":		"puti-steps",
                "unarmed":		"changquan",
                "spear":		"yue-spear",
                "force":		"manjianghong",
                "parry":		"yue-spear",
                "dodge":		"puti-steps",
				"others1":		"bloodystrike",
				"others2":		"strategy",
				"others3":		"leadership",
				"set_master":		"master yue",
				"perform_weapon_attack":"official/spear/yue-spear/zonghengtianxia",
				"perform_unarmed_attack":"official/unarmed/changquan/yuhuan",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]),   
//	三清
	([      
		"group":		"magician",
		"npc":                	"fengbo-fork",
                "name":				"夜叉",
                "class":	      	"taoist",
                "gender":			"男性",
                "skill_type_w":	   "fork/fengbo-fork",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "fork":			"fengbo-fork",
                "dodge":		"notracesnow",
                "fork":			"fengbo-fork",
                "spells":		"necromancy",
                "others1":		"bloodystrike",
				"perform_unarmed_attack": "taoist/unarmed/tenderzhi/qiankun",
        		"perform_busy_u":"lama/unarmed/bloodystrike/fofawubian",
        ]), 
  	([      
		"group":		"magician",
		"npc":          "snowshade-sword",
                "name":			"阿蕊",
                "class":	      	"taoist",
                "gender":			"女性",
                "skill_type_w":	   	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "others1":		"bloodystrike",
				"perform_weapon_attack": "taoist/sword/snowshade-sword/baixueaiai",
				"perform_unarmed_attack": "taoist/unarmed/tenderzhi/qiankun",
        		"perform_busy_u":"lama/unarmed/bloodystrike/fofawubian",
        ]), 
         ([      
		"group":		"magician",
		"npc":          "necromancy",
                "name":			"阿蕊",
                "class":	      	"taoist",
                "gender":			"女性",
                "skill_type_w":	   	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "others1":		"bloodystrike",
				"perform_unarmed_attack": "taoist/spells/necromancy/netherbolt",
				"perform_unarmed_attack2": "taoist/spells/necromancy/drainerbolt",
				"perform_unarmed_attack3": "taoist/spells/necromancy/feeblebolt",	
        ]), 
        ([      
		"group":		"magician",
		"npc":          "necromancy2",
                "name":			"阿蕊",
                "class":	      	"taoist",
                "gender":			"女性",
                "skill_type_w":	   	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "others1":		"bloodystrike",
				"perform_unarmed_attack": "taoist/spells/necromancy/feeblebolt",
        		"perform_busy_u":"lama/unarmed/bloodystrike/fofawubian",
        ]), 
        ([      
		"group":		"magician",
		"npc":          "necromancy3",
                "name":			"阿蕊",
                "class":	      	"taoist",
                "gender":			"女性",
                "skill_type_w":	   	"sword/snowshade-sword",
                "skill_type_u":		"tenderzhi",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tenderzhi",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "spells":		"necromancy",
                "others1":		"bloodystrike",
				"perform_unarmed_attack": "taoist/spells/necromancy/drainerbolt",
        		"perform_busy_u":"lama/unarmed/bloodystrike/fofawubian",
        ]), 
  		([      
		"group":		"magician",
		"npc":                	"scratmancy",
                "name":			"飞涛",
                "class":	      	"taoist",
                "gender":		"男性",
                "skill_type_w":	  "sword/snowshade-sword",
                "skill_type_u":		"tigerstrike",
                "skill_type_d":		"notracesnow",
                "unarmed":		"tigerstrike",
                "force":		"gouyee",
                "parry":		"snowshade-sword",
                "dodge":		"notracesnow",
                "sword":		"snowshade-sword",
                "scratching":	"scratmancy",
                "others1":		"bloodystrike",
				"perform_weapon_attack":"taoist/sword/snowshade-sword/baixueaiai",
				"perform_unarmed_attack":"lama/unarmed/bloodystrike/fofawubian", 	
        ]), 
        
//	狼山
	([      
		"group":		"fighter_w",
		"npc":         	"assassin-hammer",
                "name":			"搏浪",
                "class":	      	"wolfmount",
                "gender":		"男性",
                "skill_type_w":	    "hammer/assassin-hammer",
                "skill_type_u":		"wolf-strike",
                "skill_type_d":		"xueyeqianzong",
                "unarmed":		"wolf-strike",
                "hammer":		"assassin-hammer",
                "force":		"wolf-force",
                "parry":		"assassin-hammer",
                "dodge":		"xueyeqianzong",
				"others1":		"summonwolf",
				"perform_unarmed_attack":"wolfmount/unarmed/wolf-strike/duanhou",
        ]), 
       	([      
		"group":		"fighter_u",
		"npc":         	"wolf-strike",
                "name":			"搏浪",
                "class":	   	"wolfmount",
                "gender":		"男性",
                "skill_type_u":		"wolf-strike",
                "skill_type_d":		"xueyeqianzong",
                "unarmed":		"wolf-strike",
                "force":		"wolf-force",
                "parry":		"assassin-hammer",
                "dodge":		"xueyeqianzong",
				"others1":		"summonwolf",
				"perform_unarmed_attack":"wolfmount/unarmed/wolf-strike/shigu",
				"perform_unarmed_attack2":"wolfmount/unarmed/wolf-strike/canzhi",
        ]), 
		([      
		"group":		"fighter_w",
		"npc":                	"xinyue-dagger",
                "name":			"朱云",
                "class":	      	"wolfmount",
                "gender":		"男性",
                "skill_type_w":	    "dagger/xinyue-dagger",
                "skill_type_u":		"wolf-strike",
                "skill_type_d":		"xueyeqianzong",
                "w_adjust":		-30,
                "unarmed":		"wolf-strike",
                "dagger":		"xinyue-dagger",
                "force":		"wolf-force",
                "parry":		"xinyue-dagger",
                "dodge":		"xueyeqianzong",
				"others2":		"meihua-shou",
				"perform_weapon_attack":"wolfmount/dagger/xinyue-dagger/douzhuanxingyi",
				"perform_unarmed_attack":"wolfmount/unarmed/wolf-strike/duanhou",
				"perform_busy_u":	"legend/unarmed/meihua-shou/meihai",
        ]), 
//	大昭
		([      
		"group":		"fighter_w",
		"npc":                	"jin-gang",
                "name":			"雷芳",
                "class":	      	"lama",
                "gender":			"男性",
                "skill_type_w":	   	"staff/fengmo-staff",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"puti-steps",
                "unarmed":		"bloodystrike",
                "force":		"bolomiduo",
                "parry":		"fengmo-staff",
                "dodge":		"puti-steps",
                "staff":		"fengmo-staff",
                "spells":		"kwan-yin-spells",
				"iron-cloth":		"jin-gang",
		"perform_unarmed_attack":	"lama/unarmed/bloodystrike/yinqi",
		"perform_weapon_attack2":    "lama/staff/fengmo-staff/xianglong",
		"perform_weapon_attack":   "lama/staff/fengmo-staff/fuhu",	
        ]), 
  		([      
		"group":		"fighter_u",
		"npc":          "bloodystrike",
                "name":			"活佛",
                "class":	   	"lama",
                "gender":		"女性",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"bloodystrike",
                "force":		"bolomiduo",
                "dodge":		"nodust-steps",
                "iron-cloth":	"jin-gang",
                "spells":		"kwan-yin-spells",
                "others1":		"lamaism",
				"perform_unarmed_attack": "lama/unarmed/bloodystrike/yinqi",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]), 
  		([      
		"group":		"fighter_u",
		"npc":          "kwan-yin-spells",
                "name":			"雨飞",
                "class":	      	"lama",
                "gender":		"女性",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"bloodystrike",
                "force":		"bolomiduo",
                "parry":		"fengmo-staff",
                "dodge":		"nodust-steps",
                "iron-cloth":	"jin-gang",
                "spells":		"kwan-yin-spells",
				"perform_unarmed_attack": "lama/spells/kwan-yin-spells/an",
				"perform_unarmed_attack2": "lama/spells/kwan-yin-spells/ni",
				"perform_unarmed_attack3": "lama/spells/kwan-yin-spells/ma",	
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]), 
// 	白云        
	([      
		"group":		"fighter_w",
		"npc":                	"feixian-sword",
                "name":			"飞仙",
                "class":	      	"baiyun",
                "gender":		"男性",
                "skill_type_w":	      	"sword/feixian-sword",
                "skill_type_u":		"calligraphy",
                "skill_type_d":		"feixian-steps",
                "unarmed":		"calligraphy",
                "sword":		"feixian-sword",
                "force":		"chessism",
                "parry":		"feixian-sword",
                "dodge":		"feixian-steps",
				"magic":		"music",
				"perform_weapon_attack":"baiyun/sword/feixian-sword/tianwaifeixian",
				"perform_unarmed_attack":"baiyun/unarmed/calligraphy/sangluan",
        ]),  
//	白云
        ([      
		"group":		"fighter_w",			// 100
		"npc":                	"musician",
                "name":			"琵琶公主",
                "class":	      	"baiyun",
                "gender":		"女性",
                "skill_type_w":	      	"sword/feixian-sword",
                "skill_type_u":		"calligraphy",
                "force":		"chessism",
				"unarmed":		"calligraphy",
                "sword":		"feixian-sword",
                "parry":		"feixian-sword",
                "dodge":		"feixian-steps",
				"magic":		"music",
				"perform_unarmed_attack":"baiyun/magic/music/bihai",	
        ]),
//	黄山
	([      
		"group":		"fighter_w",
		"npc":           "liuquan-steps",
                "name":			"流泉",
                "class":	      	"huangshan",
                "gender":		"女性",
                "skill_type_w":	   	"sword/siqi-sword",
                "skill_type_u":		"yunwu-strike",
                "skill_type_d":		"liuquan-steps",
                "unarmed":		"yunwu-strike",
                "sword":		"siqi-sword",
                "force":		"xianjing",
                "parry":		"siqi-sword",
                "dodge":		"liuquan-steps",
				"perform_unarmed_attack":  "huangshan/dodge/liuquan-steps/liushuichanchan",
				"perform_busy_u":	"huangshan/unarmed/yunwu-strike/miwu",
        ]), 
	([      
		"group":		"fighter_w",
		"npc":           "siqi-sword",
                "name":			"四奇",
                "class":	      	"huangshan",
                "gender":		"女性",
                "skill_type_w":	      	"sword/siqi-sword",
                "skill_type_u":		"yunwu-strike",
                "skill_type_d":		"liuquan-steps",
                "unarmed":		"yunwu-strike",
                "sword":		"siqi-sword",
                "force":		"xianjing",
                "parry":		"siqi-sword",
                "dodge":		"liuquan-steps",
				"perform_weapon_attack":"huangshan/sword/siqi-sword/siqi",
				"perform_busy_u":	"huangshan/unarmed/yunwu-strike/miwu",     
        ]), 
	([      
		"group":		"fighter_w",
		"npc":         	"qiusheng-blade",
                "name":			"秋声",
                "class":      	"huangshan",
                "gender":		"男性",
                "skill_type_w":    	"blade/qiusheng-blade",
                "skill_type_u":		"yunwu-strike",
                "skill_type_d":		"liuquan-steps",
                "unarmed":		"yunwu-strike",
                "blade":		"qiusheng-blade",
                "force":		"xianjing",
                "parry":		"qiusheng-blade",
                "dodge":		"liuquan-steps",
				"perform_weapon_attack":"huangshan/blade/qiusheng-blade/jingsheng",
				"perform_busy_u":	"huangshan/unarmed/yunwu-strike/miwu",     
        ]),     
//	其他
        ([      // luori-quan
		"group":		"fighter_u",
		"npc":         	"luori",
                "name":			"阿胡",
                "class":	   	"bat",
                "gender":		"男性",
                "skill_type_u":		"luoriquan",
                "skill_type_d":		"fengyu-pianxiang",
                "unarmed":		"luoriquan",
                "force":		"bibo-force",
                "dodge":		"fengyu-piaoxiang",
                "perform_unarmed_attack":"bat/unarmed/luoriquan/luori",
				"perform_busy_d":	"bat/dodge/fengyu-piaoxiang/zonghengsihai",     	
        ]),
        ([      // Tiger-strike
		"group":		"fighter_w",
		"npc":         	"tigerstrike",
                "name":			"阿虎",
                "class":	      	"wudang",
                "gender":		"男性",
                "skill_type_u":		"tigerstrike",
                "skill_type_d":		"five-steps",
                "unarmed":		"tigerstrike",
                "force":		"taijiforce",
                "dodge":		"five-steps",
				"iron-cloth":		"xisui",
        ]),  
        ([      // Shenji-blade
		"group":		"fighter_w",
		"npc":         	"shenji-blade",
                "name":			"谢老掌柜",
                "class":	      	"bat",
                "gender":		"男性",
                "skill_type_w":	   	"blade/shenji-blade",
                "skill_type_u":		"luoriquan",
                "skill_type_d":		"shenji-steps",
                "unarmed":		"luoriquan",
                "blade":		"shenji-blade",
                "parry":		"shenji-blade",
                "dodge":		"shenji-steps",
				"perform_weapon_attack":"bat/blade/shenji-blade/jichulianhuan",
				"perform_unarmed_attack":"bat/unarmed/luoriquan/luori",
				"perform_busy_d":       "bat/dodge/shenji-steps/shenjimiaosuan",
        ]), 
  		([      //FY-sword
		"group":		"fighter_w",
		"npc":         	"fy-sword",
                "name":			"风云剑",
                "class":	      	"tieflag",
                "gender":		"男性",
                "skill_type_w":	      	"sword/fy-sword",
                "skill_type_u":		"ill-quan",
                "skill_type_d":		"tie-steps",
                "unarmed":		"ill-quan",
                "sword":		"fy-sword",
                "force":		"jiayiforce",
                "parry":		"fy-sword",
                "dodge":		"tie-steps",
				"perform_weapon_attack":"tieflag/dodge/tie-steps/chansi",
				"perform_weapon_attack2":"tieflag/sword/fy-sword/fengqiyunyong",
        ]),      
        ([      // Wind-blade
		"group":		"fighter_w",
		"npc":                	"wind-blade",
                "name":			"恶鬼",
                "class":	      "ninja",
                "gender":		"女性",
                "skill_type_w":	  "blade/wind-blade",
                "skill_type_u":		"bloodystrike",
                "skill_type_d":		"ghosty-steps",
                "unarmed":		"bloodystrike",
                "blade":		"wind-blade",
                "force":		"ghosty-force",
                "parry":		"wind-blade",
                "dodge":		"ghosty-steps",
				"perform_weapon_attack":"npc/blade/wind-blade/leitingpili",
				"perform_busy_u":	"lama/unarmed/bloodystrike/fofawubian",
        ]), 
         ([      // Wind-blade
		"group":		"fighter_u",
		"npc":          "birdiestrike",
                "name":			"三脚猫",
                "class":	      "bat",
                "gender":		"女性",
                "skill_type_u":	"birdiestrike",
                "skill_type_d":	"ghosty-steps",
                "unarmed":		"birdiestrike",
                "force":		"ghosty-force",
                "dodge":		"ghosty-steps",
        ]), 
        ([      // Moon's DOGGiE
		"group":		"fighter_w",
		"npc":          "fengloufeiyan",
                "name":			"自杀猫",
                "class":	      "moon",
                "gender":		"女性",
                "skill_type_w":	"starrain",
                "skill_type_u":	"birdiestrike",
                "skill_type_d":	"stormdance",
                "throwing":		"starrain",
                "parry":		"starrain",
                "unarmed":		"birdiestrike",
                "force":		"snowforce",
                "dodge":		"stormdance",
                "perform_weapon_attack":"moon/throwing/starrain/fengloufeiyan",
        ]), 
        ([      // Moon's DOGGiE
		"group":		"fighter_u",
		"npc":          "stormdance",
                "name":			"多脚猫",
                "class":	      "moon",
                "gender":		"女性",
                "skill_type_u":	"birdiestrike",
                "skill_type_d":	"stormdance",
                "unarmed":		"birdiestrike",
                "force":		"snowforce",
                "dodge":		"stormdance",
        ]), 
        ([      // Moon's DOGGiE
		"group":		"fighter_u",
		"npc":          "stormdance2",
                "name":			"多脚猫",
                "class":	      "moon",
                "gender":		"男性",
                "skill_type_u":	"yizhichan",
                "skill_type_d":	"stormdance",
                "unarmed":		"yizhichan",
                "force":		"snowforce",
                "dodge":		"stormdance",
        ]), 
//	兴国的医师
	([      
		"group":		"fighter_w",
		"npc":                	"healer",
                "name":			"春风",
                "class":	    "bonze",
                "gender":		"男性",
                "skill_type_w":	   	"staff/cloudstaff",
                "skill_type_u":		"dabei-strike",
                "skill_type_d":		"nodust-steps",
                "unarmed":		"dabei-strike",
                "staff":		"cloudstaff",
                "force":		"lotusforce",
                "parry":		"cloudstaff",
                "dodge":		"nodust-steps",
				"magic":		"essencemagic",
				"others1":		"buddhism",
				"perform_weapon_attack": "bonze/staff/cloudstaff/longxianyuye",
				"perform_unarmed_attack":"bonze/magic/essencemagic/mind_sense",
				"perform_busy_u":	"bonze/unarmed/dabei-strike/qianshouqianbian",
      ]), 

});


mapping query_npc(string group_name, string npc_name, int special){
	
	int total,i,x,n,m;
//	string npc;
	
	total=sizeof(npctype);
	n=1;
	m=1;
	
	if (npc_name=="random") {
		if (group_name=="random") {
			while (m) {
				x=random(total);	// 在 random/random中暂时不出现能ｂｕｓｙ到死的ＮＰＣ
				if (npctype[x]["npc"]!="taiji" && npctype[x]["npc"]!="taiji-sword"
					&& npctype[x]["npc"]!= "kwan-yin-spells") m=0;
					else
						CHANNEL_D->do_sys_channel("sys",sprintf("%s can busy to death, discarded", npctype[x]["npc"]));
			}
		}
		else while(n) {
			x=random(total);
			if (npctype[x]["group"]==group_name) n=0;
			}
	} else {
		for (i=0;i<total;i++) {
			if (npctype[i]["npc"]==npc_name) {
				x=i; break;		
			}
		} 
	}	
	return npctype[x];
}

int total_npc(){
	return sizeof(npctype);
}

mapping *npclist(){
	return npctype;
}