#ifndef _PATH_H
#define _PATH_H


#define AREA_BAIYUN		"/d/baiyun/"
#define AREA_BAT 		"/d/bat/"
#define AREA_BAWANG 		"/d/bawang/"
#define AREA_BIANCHENG 		"/d/biancheng/"
#define AREA_CAVE 		"/d/cave/"
#define AREA_CHANGCHUN		"/d/changchun/"
#define AREA_CHENXIANG 		"/d/chenxiang/"
#define AREA_CHUENYU 		"/d/chuenyu/"
#define AREA_DAIMIAO 		"/d/daimiao/"
#define AREA_DAOGUAN 		"/d/taoguan/"
#define AREA_DEATH 		"/d/death/"
#define AREA_EASTCOAST		"/d/eastcoast/"
#define AREA_EREN 		"/d/eren/"
#define AREA_EREN2 		"/d/eren2/"
#define AREA_FUGUI 		"/d/fugui/"
#define AREA_FY 		"/d/fy/"
#define AREA_FYCYCLE 		"/d/fycycle/"
#define AREA_FYWALL 		"/d/fywall/"
#define AREA_FYMAZE 		"/d/fymaze/"
#define AREA_GHOST 		"/d/ghost/"
#define AREA_GUANWAI		 "/d/guanwai/"
#define AREA_GUANYIN 		"/d/guanyin/"
#define AREA_HUANGSHAN 		"/d/huangshan/"
#define AREA_HUASHAN 		"/d/huashan/"
#define AREA_JINAN 		"/d/jinan/"
#define AREA_LAOWU 		"/d/laowu/"
#define AREA_LOULAN 		"/d/loulan/"
#define AREA_MANGLIN 		"/d/manglin/"
#define AREA_MAZE		"/d/maze/"
#define AREA_OLDPINE 		"/d/oldpine/"
#define AREA_PALACE 		"/d/palace/"
#define AREA_QIANFO 		"/d/qianfo/"
#define AREA_QIANJIN 		"/d/qianjin/"
#define AREA_QINGPING 		"/d/qingping/"
#define AREA_QUICKSAND 		"/d/quicksand/"
#define AREA_RESORT 		"/d/resort/"
#define AREA_SHANLIU		"/d/shanliu/"
#define AREA_SHAOLIN 		"/d/shaolin/"
#define AREA_SHENSHUI 		"/d/shenshui/"
#define AREA_SONGSHAN 		"/d/songshan/"
#define AREA_STONE 		"/d/stone/"
#define AREA_TAIPING 		"/d/taiping/"
#define AREA_TAISHAN 		"/d/taishan/"
#define AREA_TAOYUAN 		"/d/taoyuan/"
#define AREA_TIEFLAG 		"/d/tieflag/"
#define AREA_WANMEI 		"/d/wanmei/"
#define AREA_WELCOME		"/d/welcome/"
#define AREA_WIZ 		"/d/wiz/"
#define AREA_WOLFMOUNT 		"/d/wolfmount/"
#define AREA_WUDANG 		"/d/wudang/"
#define AREA_XINJIANG 		"/d/xinjiang/"
#define AREA_YINGOU 		"/d/yingou/"
#define AREA_ZANGBEI 		"/d/zangbei/"
#define AREA_ZHAOZE 		"/d/zhaoze/"


// added by silencer for inquiry_msg file.
#define INQUIRY_MSG	__DIR__"inquiry_msg"

#endif
