
#define FIRST_PERSONAL          1
#define SECOND_PERSONAL         2
#define THIRD_PERSONAL          3

#define FIRST_PERSONAL_PRONOUN          "我"
#define SECOND_PERSONAL_PRONOUN_MALE    "你"
#define SECOND_PERSONAL_PRONOUN_FEMALE  "你"
#define SECOND_PERSONAL_PRONOUN_DEFAULT "您"
#define THIRD_PERSONAL_PRONOUN_MALE     "他"
#define THIRD_PERSONAL_PRONOUN_FEMALE   "她"
#define THIRD_PERSONAL_PRONOUN_ANIMAL   "牠"
#define THIRD_PERSONAL_PRONOUN_DEFAULT  "它"

